apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: descheduler
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/kube-system/descheduler/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

