---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: radarr
      version: 22.2.4
      sourceRef:
        kind: HelmRepository
        name: truechartsoci
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-radarr"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"

    metrics:
      main:
        enabled: false
    workload:
      exportarr:
        enabled: false

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik
              - name: bouncer
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: ks-le-prod
        hosts:
          - host: radarr.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              cacheCapacity: 10 Gi
              accessModes:
                - ReadWriteOnce
              enabled: true
            src:
              enabled: true
              cacheCapacity: 10 Gi
      media:
        enabled: true
        existingClaim: media-nfs-pvc
        mountPath: "/media"
      movies:
        enabled: true
        existingClaim: media-movies-nfs-pvc
        mountPath: "/media/movies"
      downloads:
        enabled: true
        existingClaim: downloads-nfs-pvc
        mountPath: "/downloads"
      backup:
        enabled: true
        existingClaim: media-backups-pvc
        mountPath: /config/Backups
        readOnly: false
