apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes-reflector
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/system/kubernetes-reflector/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

