apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/system/cloudnative-pg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

