---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: lidarr
      version: 21.6.7
      sourceRef:
        kind: HelmRepository
        name: truechartsoci
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:



    workload:
      exportarr:
        enabled: false

    metrics:
      main:
        enabled: false

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: ks-le-prod
        hosts:
          - host: lidarr.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      media:
        enabled: true
        existingClaim: media-nfs-pvc
        mountPath: "/media"
      music:
        enabled: true
        existingClaim: media-music-nfs-pvc
        mountPath: "/media/music"
      downloads:
        enabled: true
        existingClaim: downloads-nfs-pvc
        mountPath: "/downloads"
      backup:
        enabled: true
        existingClaim: media-backups-pvc
        mountPath: /config/Backups
        readOnly: false
