---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: jackett
      version: 17.0.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:





    ingress:
      main:
        enabled: true
        certificateIssuer: ks-le-prod
        ingressClassName:  ""
        hosts:
          - host: jackett.${BASE_DOMAIN2}
            paths:
              - path: /
                pathType: Prefix
