---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  interval: 15m
  chart:
    spec:
      chart: mosquitto
      version: 16.2.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-mosquitto"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
      b2:
        type: s3
        url: "${S3URL_BB}"
        bucket: "${S3PREFIX_BB}-mosquitto"
        accessKey: "${S3ID_BB}"
        secretKey: "${S3KEY_BB}"
        encrKey: "${S3KEY_BB}"

    service:
      main:
        loadBalancerIP: ${MQTT_IP}
        type: LoadBalancer

    # ingress:
    #   main:
    #     enabled: true
    #     integrations:
    #       traefik:
    #         enabled: true
    #         middlewares:
    #           - name: local
    #             namespace: traefik
    #       certManager:
    #         enabled: true
    #         certificateIssuer: ks-le-prod
    #     hosts:
    #       - host: mosquitto.${BASE_DOMAIN}
    #         paths:
    #           - path: /
    #             pathType: Prefix

    persistence:
      data:
        volsync:
          - name: local
            type: restic
            credentials: s3
            dest:
              enabled: false
            src:
              enabled: true
          - name: b2
            type: restic
            credentials: b2
            dest:



              accessModes:
                - ReadWriteOnce
              enabled: true
            src:
              enabled: true
