---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  interval: 15m
  chart:
    spec:
      chart: mosquitto
      version: 16.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-mosquitto"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"


    service:
      main:
        loadBalancerIP: ${MQTT_IP}
        type: LoadBalancer

    # ingress:
    #   main:
    #     enabled: true
    #     integrations:
    #       traefik:
    #         enabled: true
    #         middlewares:
    #           - name: b2
    #             namespace: traefik
    #       certManager:
    #         enabled: true
    #         certificateIssuer: domain-0-le-prod
    #     hosts:
    #       - host: mosquitto.${DOMAIN_0}
    #         paths:
    #           - path: /
    #             pathType: Prefix

    persistence:
      data:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true

