# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-medium
    namespace: actions-runner
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set
            version: 0.9.2
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller-charts
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            strategy: rollback
            retries: 3
    dependsOn:
        - name: actions-runner-controller
          namespace: actions-runner
    values:
        nameOverride: actions-runner-medium
        runnerScaleSetName: actions-runner-medium
        minRunners: 1
        maxRunners: 6
        containerMode:
            type: dind
        githubConfigSecret:
            github_app_id: ${ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID}
            github_app_installation_id: ENC[AES256_GCM,data:LNgDYRsIW9M=,iv:fV9a6m/ZNyjJY94uawDyCP6vD7yQGsBEXd3sqzEzKZg=,tag:af4BThFe3tTPDaBC/RQubA==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:I+e27Ymjn/xStiz/m2LtxUcX7vjzObuzmvr8VGnQSQQ9qD8UoRUzUK2jWcGZg9sVJJ5RyGAi+d68Nfc+99tRK4dnQWVkCszGOy1hGhNqvOmdCkRdcL/fG4UezzArvtWIq9X6VgfcPzmFgNajk/n37rsPnjBsxe8DSqhN2xf5ItgL7DfcXvxicJErkUGQN61xWqgC4/EvbjC8BPD7Ywj2zZRFheqIIkIoDQeurHjVe6/czl+3ZqoM8Vc3RHTp2SSOx8v0TQVJgdqfT3DNeDFIKVPdKZ4vqK8KUJUa1vNdYbe/XpeX06D7kIAmg/MpCnpS1ce/mGhENW/pz81RmCE/KSMmUtwEFaVq/R8CtHNN6clvnqRe1LN8eVzyZPt0xO4CxXUDcwAoxylpeecZ8rsdx9rLtkIDEDnHmBMTVLsMe514eQson4Iyjg9K9o4xOunsVslsmqq2hsDpWRFDBJA3swcZGgeTDy9bYQvfxnKMFt6kPllhgA/qQulBKfBR8sNfgXAb3dp/iXaFSPaJKTi58W1B+9l0dFAL7DJrI8LR0kSW185HMxm+0j2p0spQVAA9UrHLHxEVMEuTSuG6aeax2fcYVstcV3+0+yRGK91pqmP58flZMpJQqygpar9NGYzFvYyolqg4FIRWDybZc16gnmrdXE1XfOKOTxE/6g9mF4qXY0WP2IrCWPRQcWuRH36ydjygHvZcdV00cR6DOd3LGn7XgQWWs4JdXhjkmdZXcyHRa/uiMNtx0OR/2IARRFLt1LS5D9HrQgIetp+5lIBcxyVZ4iuiGmqotrcOxFWlNIlBW9H1JG7BWmgg8eg5udpwSbKuU+ahdMGIqHk0mCjXg09/vTLE8uSRjB/PMiLZF3dFoihvvmMqbncHwXDzigIWFdNquXyS5iIJvLmaoNNaSsJM5oq+N7RQAFDUvadgnqQmrb0GWG1+HO44t3KQq//w3R/4xUhIr6A15LYyaZH7aFL4UJEX8jEEPRB+bZuqVSVXerMBk2fd1JulTreC4vfR88JD0dCt6X6GBEyrUMXCLEM7/1Op8fczmOjU0/G9P9L/rIarIFoTUgMZnZ2JDi6enWeJ7v5sJnRiJWhWcQOtxE/fkiCiZevcnim9PJl3cDw5jA5+C5AvdbBWrq39vCh2EDdjXPC3PAOlqQ5k8Q18LGHa/QeXHpu0DNLBQAJZ7NZaG/TwMM2rm707wdOSwbOxUDqqNpkCHIU3SPfkgAExuvVuRRjTOq3BFC0V9Iv2fp941RRYUxnJ1HIqH+mbT0zMTARVoApBzo55senx8ChaoDqN2FWstxvI+QnalTJ47YROn7luVlr47GwIMV0e/rWJeYR/UrBvomioOsAKGdb70JvjR97a9S3/YNvkCmP0nenb8Sy0UY8O2S+eCxXV2Rrk9jz5/CFHg+HQhpgNabOOEc9d2cLwnCirW6kXD5+Ji75Ur9XyLBPWl7Zv2VLZz5jBQGIchqOu0O+zwCPCyqifRDNxDPYEAXR4+zR8rgTjICfIRp8M/uI6uljV2VahyIIfvQ/t30EYLltJCOkPzBse2p1qtal6hrzONlj+XVsGJt+u0y4mpterkw9BYWO7/ZaOvU3l+t+RJZZuAOD4HktqNxuCSFmirfxb8pN2EmQ/2L0JyTCV9AR+zpoqokm/pVNcx0xKqnb/tStBJcOgfT/rumiVeFrt5tsL63Mw9S1+Dq4mO2CypShOrDVre2CS6CuwareXx/sO0FuRBsP+2p+WeNuUMSaIksSEuOq+s4xzwfUEqea4tIgp/dZVOQdY56VZyOR1lOnTMUZuAGTOXjXFvfs+yFfR+Ocm6Lld2lssyq3dxsB6zF+tlGcH3lkWz7Uc90ZufuUFtrCKY1FL6/hiijQQL6mRdzyhhGlPR+lBFQ83ft2Yp3I/RxZHCn7niL5L52NVXczsoob17XePUA4huO9eHR10MiLA/50nd/UKHLvDKoAUT8RrFEHMeiOIMJCUxlKuoXZAepPSzJUthwQXbZznY469+DCJUdq/yCSD2PJTFlEaj09fgs5dKtJCSojcri75+p84qQJ/FT+ERlyjtSQoraymaGq0DpYqEYqlyfHQFRzO/Xu65uM4Z58QF6zmXYqcxT18tOSkGwq+pa64wCJd9QKyRIZTtOmnoa4hBEuWn9ilte7FbX3Svm7lv3y0gfb1Y3SJ1bwM2pTdyEtBAuXQxs4Vej0ShznaN48SZg2Dad8Sy1HAtocUVQ==,iv:/q3MEsVzW9mtv8UDTu6HhzimcqG9Tm5JXzCeqvqBHCs=,tag:/WT2UxOQzh5u5tM9AKessw==,type:str]
        githubConfigUrl: https://github.com/truecharts
        controllerServiceAccount:
            name: actions-runner-controller
            namespace: actions-runner
        template:
            spec:
                containers:
                    - name: runner
                      image: ghcr.io/truecharts/charts-ci:latest@sha256:c5cd9b58d7cbaae65e5f5c4d8e6ee3c5182d6645ba0166863051ccfe747bb940
                      command:
                        - /home/runner/run.sh
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY3pjcFNLSkZwL3BUVVhr
            K0hGaTUxb0RoSUpIZFh4S2hVN3VtSjk2RjI0CnZSaUJpWnlRUFdpUUJkVXFTNS90
            YmEwRFpLRUppWnJDK1k3UjNneStTQ2MKLS0tIEx1ZXFlWTl6YlVHc2FrZWJwQTdz
            Q0Q4a3poaHpBcEdBSG5VcW9IclVmY28Kzsz0qfKcWRG8Adx10vS2XdqrSnpHmiRD
            IyS9xSRckVNj8uWgVZTr9CB11XuYc8sT/lRf9PPHXLelucGy2D20tQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T19:01:54Z"
    mac: ENC[AES256_GCM,data:4bCTTeXzCJL7jKDfQKOtJ4rHzXVeK9vBMM+WObbI+2KMNjSrHScoKsk6wzpwP6Bwi/7BCdgkwx/G34/+vcNMRYZs+WtaNBkICQ93steqq93QrdGPQBKx8mlTQPXwUkKKOvhJlZepaeLMwTPEo+cKStWJXMonGhr+PJ9HTpgUWLU=,iv:7vLQIDQAuAYiFttody2i/vlT93JVaIhm1QfIxvfv9DY=,tag:V+IJLK2GFXLHqj1R6aA82g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(github_app_private_key|github_app_installation_id))
    version: 3.8.1
