apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: snapshotcontroller
    namespace: kube-system
spec:
    interval: 5m
    chart:
        spec:
            chart: snapshotcontroller
            version: 2.2.1
            sourceRef:
                kind: HelmRepository
                name: piraeus-charts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
      cleanupOnFail: true
      crds: CreateReplace
      remediation:
        strategy: rollback
        retries: 3
    values:
      controller:
        serviceMonitor:
          create: false
      webhook:
        enabled: false
