---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: radarr
      version: 23.19.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-radarr"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"


    metrics:
      main:
        enabled: false
    workload:
      exportarr:
        enabled: false

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik

          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: radarr.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
      movies:
        enabled: true
        type: nfs
        server: 192.168.10.21
        path: /mnt/tank/library/movies
        mountPath: "/media/movies"
      downloads:
        enabled: true
        type: nfs
        server: 192.168.10.21
        path: /mnt/tank/downloads
        mountPath: "/downloads"
      backup:
        enabled: true
        mountPath: /config/Backups
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true

