# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kubelet-csr-approver
    namespace: kube-system
spec:
    interval: 30m
    chart:
        spec:
            chart: kubelet-csr-approver
            version: 1.2.5
            sourceRef:
                kind: HelmRepository
                name: postfinance
                namespace: flux-system
            interval: 30m
    values:
      bypassDnsResolution: true
