apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugin
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/system/intel-device-plugin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

