---
apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    volsync.backube/privileged-movers: "true"
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-controller
  namespace: flux-system
spec:
  path: ./cluster/apps/actions-runner/controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-large
  namespace: flux-system
spec:
  path: ./cluster/apps/actions-runner/large
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
  decryption:
    provider: sops
    secretRef:
      name: sops-age
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: actions-runner-medium
#   namespace: flux-system
# spec:
#   path: ./cluster/apps/actions-runner/medium
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   prune: true
#   wait: false
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
#   postBuild:
#     substitute: {}
#     substituteFrom:
#       - kind: ConfigMap
#         name: cluster-config
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-age
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: actions-runner-small
#   namespace: flux-system
# spec:
#   path: ./cluster/apps/actions-runner/small
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   prune: true
#   wait: false
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
#   postBuild:
#     substitute: {}
#     substituteFrom:
#       - kind: ConfigMap
#         name: cluster-config
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-age
#
