---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unmanic
  namespace: unmanic
spec:
  interval: 15m
  chart:
    spec:
      chart: unmanic
      version: 12.5.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-lidarr"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          traefik:
            enabled: false

          certManager:
            enabled: true
            certificateIssuer: le-prod
        hosts:
          - host: unmanic.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
      series:
        enabled: true
        type: nfs
        server: 192.168.10.21
        path: /mnt/tank/library/series
        mountPath: "/media/series"
      movies:
        enabled: true
        type: nfs
        server: 192.168.10.21
        path: /mnt/tank/library/movies
        mountPath: "/media/movies"
      porn:
        enabled: true
        type: nfs
        server: 192.168.10.21
        path: /mnt/tank/library/porn
        mountPath: "/media/porn"
    workload:
      main:
        podSpec:
          containers:
            main:
              resources:
                limits:
                  gpu.intel.com/i915: 1