---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: metallb-config
      version: 3.0.10
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ipAddressPools:
      - name: main
        autoAssign: false
        avoidBuggyIPs: true
        addresses:
          - ${METALLB_RANGE}
    L2Advertisements:
      - name: main
        addressPools:
          - main
