apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:eIEk8M18CXRboboW0jpbBCi9PtDrVrxfh9z+A0wc/xghtgJW3lUDzYsMD6k7vcoArLDzDDBowxokultDqA1UWTfVIOhirAJMuI5Z/v72FeOGh1chp3I0iRGZljDnI3JEp7lCQlK9JoWlc5ZobCCP0IV2E+7kPQe613S8/eM28w20nl7WviGSKJX8gNrsYDt6ZZWwevpYh+6AD+pFV+iBFoRLp+vTnZwg3fFa/NlorhRhwrqPrIe97zT7FSvLvkAK5jWYALRT8EPZhIgk//3TMLTMw8VAjIqfD2i2OXKJHmzwUKuBozx5Npe9zyUJTqMfVa0SDVy993Wj0e7gYR5jdSMRut4z7lbtH9icJI45zGb4PJKdN2NOREEO0voqfKge,iv:kec52xs7nO5fML8cwtp9k4GdBR9A3kCuKG/YFkgo1sk=,tag:fRBHVmk6iozvrEtDtGRc+Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZHGkjgV/DlliW1zToh8psaNEspbd/FCkqbHcdnckNDy73Juo8vC1EHwdrPse0vZ9P05pzAOxvBESnjX9bExdLrD3gCxJnu2H28KteQE0NOz15k1mOJwM9Yk29PGUsZ03zrZY7xFOgBKIA4i0jONbstbvOs39Gz0ydLtMbUeD8y83NfTlbxaejJ6cfmLugXHqzIRpwz3PMzo3ZrAyS8SEwyO10YfIkT96jKXFp1w0B6s5xWpl6XuNgHGc3Fd0TNTV6dWSgEF/ZzuKQzzf1g==,iv:4UiTVq+/HuOxJ1ViwopNPX/cZlRYR3Z/kLeJIXvJMUs=,tag:+1X2MuUN3N4XE7LdYXE23w==,type:str]
    known_hosts: ENC[AES256_GCM,data:Pf9bgpP2efIGQNwR9v5Ut//Vdn7i7epzsTFo5OL17BTMQ+RQe8y1XWl2tLXXKEk/QtaHJXW1APEuBS2LTpf4RuPILGBTPm/IPhAi193O9Anb1+yBrOlsJFA7SPQq3uXm+ld86rNvrBENiXJN7KrcFzpJia5uH1EwC0e9cKu5TaJqtJ0KVqvanpzJHKWq+Ri6xMQUA//UQ4tfVSbv/2g71n9Ew3PNAmUSjs8B,iv:TrfObMEJsJZYPwZPeY1LrNmthUKljiCGaic/piBZHyM=,tag:EhYvkezVsEJBUx9ogX1zcw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNHExTEVocHRXcVhZd3pV
            bElMNXp4L0xNMUM3QU1XaGNDNUYrMmt5RXhrCm5JdlJTa2NZTERhMk5kTUw0NSsz
            M29YNlRIWGxWTHh2YWxzdUtFT3VNdUUKLS0tIGVvNjk5OTlQdzVIeFF4Sk1UdHF3
            MW9yS0IvMVRLcGpLQUs3azErd1JvMVEKUL/yusIBhSK0H/oZ/oRF7DpfEgVaKlrD
            QW+L6rHmEEtDYMv+ef7Np4EIe0j/Sv6F/gTFKjzntOkL/eXiepqWtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-23T19:35:07Z"
    mac: ENC[AES256_GCM,data:+VF/hvjT24nQhC1Y3DJicEc2LpoaV29vyHbDjuTGmuiV0bgQqPDdhy2UDwtt2utjrrZAq21MMohuI3OCShcQrZzOr8IoBc0mryldGpIjT0yo9YljQX7RtYdqH/KP+iHDIR9GAp2tQuASjagg9NPwWSqd65dlNhOnPOJOrOebAu8=,iv:HuTSBavyPqkes87B+pWN5VEfeACjBkm7x45pe2bGDC0=,tag:bN2LW9wPYCL1CVmU55lpaA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
