apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:CCY6hdmXiz1x6aFAyw3Hc+CP7tGKvoupa7au+4s4UH8jRZEF3w9y9bSf9N/HB2rIaHqqo4G7YtDNDXnnlj48buFXYxIH/MN0FqGUjOePpItqYY4wt/BgbTScKJUpeyq4hinQ6IOM17Q5AAltHxzIBVF0vAvHL7m3je8h0ucHYOHz7TXssvweOaP1y6nwS6pCgBs27pZ8yMnJBNVi8v0vzfhkWylzoTL3YWDfO0kfQYBAHCjPENJuZwRLy0+IVVkt2G46V89nEfpFkZ0vHM9PesPg4BtQr74MDAu4X4IEPvwTONfXU3/ANAiAd0EFLcxRqSMM1G5LMVX6N+Knc8nyUAmNk0wxJkRA2nIlVnKWSFxukV+1JKx5zF4rRa8XPpzt,iv:Z+ylnrAOWZiVnCNDonv9jnUM4QL6JNC8Om+KJHaVh7Q=,tag:2bNZifDB6Xn2hDATKRYI7A==,type:str]
    identity.pub: ENC[AES256_GCM,data:CkPi0lf/yz2HbysO2BPLKAvNhpXjmS/A7l8COb+/FWXaapmeCeJu4MtS6wQt8+lPTflWyCA3OCcX58RB2HejD9jkk5UwMZVDuVcHo29jSaSKWs+kKlE+GDB8NTsx28IkIEeFCB8Mim0qM8wqDhJMWJnMfkxKxdFwRE8bDWfnsVwYkEAebGJK4h3OVqpx76xVjOdfeny607eecNUbU9Xwh3MpXgdYeq9L59bq1mqEzofRBOXpgmEWz3YyOCCiowygssx5p/UovC79KfAIeQ==,iv:NNVuRsc9vUBG2BVsQ+I/GWmF2gVuuGMCI55mZDj+by4=,tag:3fWCjOryTAzkin8F/tQDAQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:/1vxUmRhOG+wNAivFvgeGqTGkiZArxK2vWYCk9TQAdL0snmcmiPIfYafZkoOxc2+nrBat8dmOGzu5clJ44uR1VClnqHwRbbzMmMDA4X5/2YJB1tMfE1blhF/UmWPDkgX4Sz+yG/2TtmteVQk6cRnW5+Pv67nduB+oCIua2pWTcj11EjqCDkh/cdEMRbLhL5Fzyq8vwvLugifTmFgwZEdsp5xwwDL/cbu3uZ0,iv:Qel/xQMUEr7R+du+Oj932hN5m1LmYLeCtOlzgQ5FvbE=,tag:BwcHU3bHueRNnEi6U+2akw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRDZoYzJIRVVwZzhVNllY
            UE5jS25acU4xb0VYOGpuRjNxT3R2aTVTKzJRCk9oQVVmNXpUS1ZjSmxLd253VkxK
            TTZxTW1MeEpQc29QQnVvdVErcVVrMlUKLS0tIHl5REhwcDZLS2I5QVIyWkNEZStZ
            WklPYUU4c29YbnNUbnJiSEtYWi9xMDAKTA7XmTLI/6sF6YlxJHnQOpI+U/7vzOLs
            jve54Z0wcLoXdnqWvNyxRdSTgg0rgWMcT2nbSgW1kiQ38fKDSYCITQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-31T18:24:34Z"
    mac: ENC[AES256_GCM,data:H5GchxlnUV+tvAV1kMMtSEwRKc72vjwdEE1j+JKibntvD8jwIOYVIHoTed/qLe83XhjMRg/8Da+rlys5olEvjuzW9ncjbM0D+Mi4XTOS2iJOVOFHVCViNT4E1tzbrJOyz4DBTBQcHvk2+Lf1K5ycIYNtYAjlVsRgEMDuoCadmVM=,iv:LVuIQMdiMvyyJ1DrioJvoQNMsNPFtmlXBwDDZaTWT5A=,tag:p5RHEOUwQmi675sEhBrkWQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
