apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
data:
    identity: ENC[AES256_GCM,data:w9/d3Vy0qzseSdKBg6gj5jP5yryDIUNt/KIzAiXuiTJ1ej45NMHqaIElTTeu6BKoK6Yj37Ndm3wkRjKwQPNfZWzxzHXHtS8yOfz8iFYrecsUrNzwo0CbCNoIX/fJPxdQnx2Pxg2QJaM/Znbro8vkXYZu0rMJLx2vxrOOOBE3k32Tbx2caWzaqeFdMpjg9Qhvfzn9y5xBaE8NsXWZPpXAcijAnfDEARsBiWHHPIbENChyA9s7lU01LRdnLOqtjCT1Sbxn8KRYBL+T7ZOQTCtP6ho2MNwtT04BkT65T1imVKokGtXRUr0Hf/EnZnrBziaDiwNvdUqeT1D2mm8f6E0O+iTlQ/O6LdbQ1lB2T4At7ryqImNFesiNNFFXuud3T1iJS2D5Exn61OlD8rm9B1W2nzQnnkEN8MvQR5FWYg6XAY8AKGIc+IJKoRf2sYjjbjFp+7fWY8zAzt5+MYcxcBklPurkvkkIRqXQG5PqcBmlGtR6a92HH+IV3KexR98fEIn3FFlt7wowBrsQuNlNs0SpUkrR15Hcz0g7,iv:p+c5KDf1V15AAMGsApLbQ+5X4lFSjtY/8PybevHjs4s=,tag:w1L+83QzFJA32WNUfRnYHA==,type:str]
    identity.pub: ENC[AES256_GCM,data:+2V9jjQYDwCqlE/emO1WZKrc+/o5IsFtY1G/qXAkmoyox51fOa5L9SgrsAckKaHEbw8iH8eT5xJ5jAYBTkU8Xb5zIAwjILshNtt3GHTOHO6m1yzgdX6VfgoPeE8jItJRgQ0n+g4BXZwdV/phzjPwnoVT1IWpReMwEglHgZntsZiicKW4zGZ8lrICV094XQ2FGAbmFfL59IvJOoPg59NzV/pG4k7PWjgJyg2yXBdZeLuogrgz3lgD7qh/jZZGfDg1CxxpXisAwgSjLXyeApWm9soKbSSwqVSPw1LhErUE3ToW19zyAVK3LmbWgJBdeC5XMkNqmyuhm84d/BcQ01jISJHKJBXM12lIJi6V8cIZRGaA+Hfo,iv:ziMNYMgnd58QadWz3J5ucMroxM+QSLqQ3JBBHYCOho4=,tag:3e6QT8y+a0vzQZ9BKAYTnA==,type:str]
    known_hosts: ENC[AES256_GCM,data:+K3lPyadFH1ZcoOCWyf1rAoETvP2tPdQyi8H9h67gj2Z5ptfrCuDkWHxE5td1W8geFFl4ielrXtdf2w8kZjCEvUgqCCf7lk43Ynl6uPMyIkDeyCAMf5FttRDjcbAvZt07oJ9QWTLMOYU2BMYngJHRxVtg7cnZka6AGNYKmyZIJRKov3FwSG7WNqwdSQo8LnwumLirpydbpcLe5GPQ+oe0Z00qcGIRLHfykPUAv/eRpbbUVEMVgbxRh+uBv2D+jAFoDvLio+TgCzPqeNBqG4cKhL1RklHWBS0GqRMxt6m2H8BZ8A7,iv:p48Xei8l9fNo6flIbk5/6ImXdfuNDX29oz/RkfJnmxE=,tag:nGzF5aU728Ir+7YDzxlVBA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNml2VWJXa3dKQjdaQ2xp
            WWRtY3RVRUR4VkdaekEveHFOUkMvT2FJdUJnCjE3bFN4K3kyVkdpQzZBbXRnTkNR
            dmJyWGhLNkJuSlpxWGZ0ZDlPVlM4ODgKLS0tIE5udGlUdWVScm1ZTndVMXh2akMz
            ZjhMY05CVDFTME5mODZoK290WjlGK0kKB2ljRjcFRSRc77u8MssQ5GsPs5mEZqi2
            Aq6Drr65JNnPCwEamApjxaWBCRpQPFlo80LJGzJ/f6quJd2kn0nVpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T16:14:05Z"
    mac: ENC[AES256_GCM,data:+iFStsXdiAwq0vw87rmLm7IBvBZVPquAlZh7ZlQFEXQq5LXALUiq67CfN/NvNGiXHTnMMfPTt9Lkn5CU6mmCqLwbsOgyo/A7ShejAH77ezuwilPSoJM/lOKBiJqlPprUYHC5njAw8p0bvz7XfjIz2Un9zCptAOQTt1xLd6lT5Lk=,iv:zvZoTr9uX/NrAjJi+GJ7s0PXwVYGXXVp6mwR+JEr44I=,tag:7yn/9SClXCymy0jl+QIYbQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
