apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
data:
    identity: ENC[AES256_GCM,data:7RDgkzTwi7GgHMRk1+yNFVStyGjFj0OZJzPjYb/gqSJ6MAooyhCQ4ze7bJAjYPd3GHwBjVZjN1VQ0pkyi6lUnJiBi0aSkiq3iCmVsxWo4Fg4qpnze93s9xrD2E1zvICuI1KGdVavd4DIm79yY39aiVJPkEBIR7cwsiXgbpJzFeC6dG0XJPyD5HemKkb67vWJIumxjgAl7MaXUzZA/Gy2xr1OgC40o2Tjh6t4j9O26gOz8e89lUFQsOrfPZMuEKbj7YuYABcvPYh3+EN9PosVYOwGTUUcPjZNC05srsq0mwQYXzvVbsp30GgQy9A75WLxUlSDldnMJLnkwi8WUizKdrIRsh4+ajabcgLtelsd5uwt/dJETLVf2NpxWR8W0hkcne5IeLr9KB30tuwLckF3DSOc0BqVkeS2EOVoV4FcfvEJEisG8iqBk8FGziod9DQ2Hl/zfDsI/XgrQWewpGogog585BByoD+vfgIrsTrfAHF2fmt3uVBilb1lBS8i7YS2RJryXTxOCAsM+FQ5vSGxBfgQUMXnkymE,iv:Qs84FYTj+tm/EFCVxSwysM7LjK/o8YMR6fKUV5Uy6bU=,tag:18DsT7DU9Cq+g/mg3ds59w==,type:str]
    identity.pub: ENC[AES256_GCM,data:K4hKovF8t29kIeZJn7QwIg4VdQqgeEhSlbIqidx+2bu/3xlhMT+EhBPGFgciN1leSn9qf8zCNm8KivCLCWqXm+2juxhh/oH+fX+F+75JcOfQkZG1mWXbOMzEc57K9dOgREraCVISnurcAtJ7gDdsJYE8GcCJS35iuFC0nnum6FIyQpj6+xvJp1I+Cx4utHj1DeX+636tFpRRo+SNDI7Lxi7meTjIJQw2njSz8fRltkknBJfGri2JEj+gjOaGLngvKQEQDZji9It1F4J/j0Y87Q9eep2yoOeNOkKLeQjF8w7xF2YSamtCLwYloTxVw7eXc1bautWFdPNhFqxjz67/bMtPKQcu6Gn26XV52m2a9d+PGRiD,iv:IKkThYrhse3rVe9xqupBled7fSqvGgBZBWItJmNTSgg=,tag:uWJ7jh6TH3106B8xVg50Lw==,type:str]
    known_hosts: ENC[AES256_GCM,data:/5Rex/loyU+ERJr+5wqIdK5QwpFYZdxkFyfyWqfJUW4pGJx5G30TPx9N4IJNai1glqNsX4vvh9uKrVwy2G5dveQT/as5hdjs7BgoaS/ZXlMG0TaAPs7UQGM9ekALNicitUYMfHqV5E9ZamSXxavwpuzSVHpTMk0A51pC9EGywQ3ZrJS9HWZ50BhPwxjVxMjztv0nSMxl5p6y57mtMospSC2ED4QNhpQZ8F1Plv7LXTZ2NYoqrgHso8tr8yjfOiNs2nMOua1okZ340qZsD8GNpuupY3pTojHmkwbgxRq7S1d+aQw6,iv:xiWfAzjAe+X3mLZ07tsw/s3BXSz90bK+kvk4m3N6zGE=,tag:yjiP7cIktFufKIy9SLBbCg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OWRPSjFyMXgrRG5Ndjl0
            ME04MGFYUXlVanY0NUhpaEJQMGQ2dWxJc1JNCjZVc2g4MjBCbnJ6ZnJKVkhnT3NR
            VjlsZ0d4OU1VVHlxWHlJTmoyNkxxUlEKLS0tIEl3a21hNldKNVBucXlZOWJwaUxP
            WjJ0TUpPN0hnSFdwa3hzMnJiRi9vU2sK+W6IXAH5DdaNP4oVAzd6FlWysS2UNgPR
            Ar3wdaxEayT0FNINZNNPn3HQbnSdBX4jYWDALhdXbgWeeXfH0dT1xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T12:16:04Z"
    mac: ENC[AES256_GCM,data:4UbJWavNJy2l1PB3pPV1jzyyf/LM7cD9wCJkqOzNw7g0Xc1ybzebJzBwQl50KNZBCCOMB7RhAMrQw+tYbLB8lqlj5tW+WGfvV4W++nD/EBlyQKCurQzpCUKYX5GBfgAMnyzMnzWgHsSDyIYzQf4YwLFbLbkOdERzp1fw9p+SzJw=,iv:wBHBZJJRp6a5u1UX/ZM2M2aZBziX/Agf6zoYwXe+2ks=,tag:7wAAo6VxYd/Cy8WZR0hmtw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
