apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
data:
    identity: ENC[AES256_GCM,data:OPKfp6lWAgnJE3f1M3s9ESkszCZRTzrDSQbtJCOIDqK47xQekvPXStRNAscsuwv8c6bUK7BPBiFsoPutz/fxBOrDehWEVfJ5Z0OmWOuMpK/SmrJ9XM3C7H5veDsZGGHhK9/HBL1GELxbsiifepSiG40hzYrKhEKgJfyR2IiWhv4Wek5ZFKoeM/oYkYcuZXe2Le6yRWnnQMw3N55gkbwKjsJe6kXckQOSTifQPJslwwESk7rXV9eFsqrPGndxt085i16So554yHPkT1QK2Xf6xfErTQ/rMvjz6Wvl97HaTf8rWM5k6GWa//1hGOj0N2eKmjdzE5WJ/WGmXoYWVyp05ax7RO/4FQn2MajJiL0fYL1IgATUEtVnAAiBc7R1CtiKHGaBuOD6vEKzb6GjaIbCf4eOYap+tVGCu6Jl5R6YyMfT04CfB6E/ylHThcSMjOr5OETGJEnhYOdGZN4Rhf9XQL9YULJ5WvMrgXb3soQqvm347QM2SQk3Sf08A9Uop97CD8EyEasVCEl9Y8n5u25AoIeablcCP1Rb,iv:/HLV9tu3384ixXILnxQI+3RCI3QpW7qRzkHixUYQ/RM=,tag:WSsu7faOP/AcrXjmIqgkcg==,type:str]
    identity.pub: ENC[AES256_GCM,data:K4WnCgfdu9McfI398YK+a42J+Ba0ZFvkQbbfcL7TnEZk3a+uxYHhehA9tlt4IEevCxiaGADAIf4t55MTrCrYx/OcHUDgbiHG1XAq7cnFIUtJf8GesoNXL1Jk1Pu8ZCRyWXkr3jRiE/Y8y6GovTJSlEKy50sZLrjSEmsKOPs9sHUBNGY+cy2DkdQFE6vRCDBtChTokIx2M4V8yECbmRlo5tJo/4t6+EMxCxj1iQKc+jypHhrtVquLtpltEI8S5Mf03XWoWw1XN0RPJteh/BgS9rYOA7MV/hvjs97O9jzExiAarTUMqAyGftaqLsRph+Cfkvp2QhkpLNqpJ9oQIENdYvU96316WvO770gH4FqHsEzqv5H/,iv:EoslSTRvcaDk0ameLjyVspX38jduvRXDzT/cYIU0B8Q=,tag:PD7RBM4ps2BIyLW1+VAoWA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Ozm/dxQLXLlzDG96w7t3jT10F3awlYaQKwHcuAnXo+VzZHmWdNEtyDEzcFg3+p4alZBEYTkt5HcM1bsPku9qkPZbx8wnsp+8UuAsTVnmeippoie4cqppWSATtmEExnJECqcdVmwoUuB0QmdPiO469Dqgzz+09MxpTsIFHxRz5gml6NIWAl1lfGGjgUmFfXiKmXkRbW9/UwmYKDtSPTBfy4zdIIovVRi0/dg3SB5QtyqA+bQngMsx6fDGcVLJfI6jumukvbLJu+NPcH2Zx5Osa6kRA3vB5G8kdZ0xYGLlHd7L5tKx,iv:1W0mRmwuo0uQQMa3eFwKqEqCJjFOaBsT9U17ggGVMGQ=,tag:YE2sJUqJmBWusLgBJPwHIg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSWNZVWNGTnhUMG90aDNx
            NEdyRkZ0TmcyR01wQ0Z6ZHlVODl2YjA0czBnCjdXVzZ0OWdWNVpuVFh0bFo2dGxs
            cGtvUHowcEdDWFhTVER6aHkveGE5ZVkKLS0tIDBaVUdHZEh0a0luK2FKVEZaOW5Z
            Y1pDVUJhdXkzaUdGZUIvRHJ3UjJDeWsK5pfrMyDDpUCd8kTEx71qrZxBzBsG5ByZ
            Bah15xmop+5GszP0M9Lan6E0opSrNYCuBa4fEH/jCdAJDmWSDP2qyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T15:25:39Z"
    mac: ENC[AES256_GCM,data:SZxw4SdUvx7D0XJPR0Q+egJvcAlklvqo14s1YvhYs/hGN3vTrFycs7/n+NEjzz4YggLdMU5NuzKy98Hdwtu2N4QZCXBy8W0tWoJvLGS0WiMH6zqFdkJlFoyHRa1SZiNAnGRmqRiK3D7QCXoP5HzeZBI9/3oEnI/LO/lGsM6N18w=,iv:wigBVlgpNDu6L6bungADNhESaXKRSAdizHp2WK25168=,tag:yEjXa4NC+ZyyL+VzJQ2noA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
