apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:I0gGGB4g+H49ky6NR/sWc8z6CZx1K6WpqJvJlLUqNTX56eHe2E6OatG66u3TPYovDx6lEd+4m3KPCW589mQRudqIuiiizuNcvreTuEtYkIUDL88jdekVpbXK/Y+hLVVz1qXar4zTQta4CBcMZzfiKrQqKL2ti2v6LgzOibCdIy5L8C4DKjm3klhw0Lq4la2sngsoKbiXPkg47SjafxE11xq87OZlncm1jVvRTrSfpqsbvrg8ZB6L0+3W4UBR8dRiOFA/yMPYou5DvPTHOCDDOhUSQ7ndkwkzJ4cyhT1faRFWc/njzzEV4O8O1uy9VVXF/PSssDMD1eGkC2ztcrErOSU5vE915HvbOenkYNhIZquy+ediHZ/DuC2yNCTjXoPz,iv:c8dTfAxLnsaz2e9AzHfm41CXeJqhHLHjksPaU3bgO6g=,tag:YHkZ7EjbiZQYe8YTshkyog==,type:str]
    identity.pub: ENC[AES256_GCM,data:QvBtDzbzqyzecKRmmGrgOmmy0bi2o1jpuGMK63/SnG/CncKIkYBUnUhMapHjPNyWuiRTYpW1GbxPBl9hGSHj4x80aystHbIHLcJ8yq8832MVzxfwJfYlkeY7ACidZ9NQ8fZlT6s7bITvJphg7VKUUmsPK1vrA+fD08pIbozKKo4w3ckqmjr+ZQG1/yOk42ZlZGPssrSvzmQXmNizt8CldHQ58U398O4BCDAEmdqPCFtDVAWV6QCnwiiVULjH0tK3JWFGuGT9GtSUkQwxfA==,iv:7NhHtH7DBzXHdE7mW5TDILVHK6Ovz6dvjw6CoMXA5e4=,tag:L7VFSPCVpyo0kJ42GJPIGA==,type:str]
    known_hosts: ENC[AES256_GCM,data:hxuoWRD1OjMtgAjbGbF/jjQZ/UiD6o5JqIZmzM8GNO9d+gtLVr9B7PloYXdYIiLxjjAf6b7QpqQH2uy4OE8xD3sAcYmVHjLIjnpEPu4IKJlOQ9lnQC3g8rH3e2CLI7NUQFjQ+IEIQQ1qyzNE4N796Hq97HJveseI1uv3LEhcbDeGXG4PCNwQZuJvHh4HwHR6JEwz80zyRaaHC7AjD7CC1RmKd73HUsO6mDsA,iv:FHnV63k/B8xI4jzkrumir6eTyfNhaPyCZvC0vXfqmSk=,tag:XDfAoLotDnuWECey4UuNSA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUVQvUnF4Q3VFenVpN2dC
            dmZYemQvNnk0SlRWbUdyQVFPU1hDQWpXMFI0CnJtR1Zab1o3SE1ySmtBMUxnR3R6
            ZVZrNkN0Mis0MlVaVUNHRG9oQTFGeEEKLS0tIFJxcldGT3lYMUxpaGZaZUpFbEFW
            OEt2aGREc1VqbjNPb1NyMGlmcktOQ1kKZ/CQHhF/h4xVvvAHMzk2cYG17NZtv30b
            Nb5sVWPkRLVVKfqYj04n09qpiDI4bsUqRv/gOiWMzZQ9UNvqo56flA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-05T17:20:01Z"
    mac: ENC[AES256_GCM,data:U8dPFvkoxlH9NFeqB/mDfOBwq9ecwUGxf3OWVZEaD+2FobKc5/FONfdN0RUNekUAwDOMkAhWD4YIrYbeumqmMhALbHZeMoHmANXhhcKdQGwoCqvHhUhAlh0rMThR7Gy+sTmbJ1jvHg4DaFDOHfjbEXAE1QcFTd2mrMQjStKCgds=,iv:G3A7zKrRwV5V5I+g9/fWCJXhJX2T74WQ9vQGRlbvmfc=,tag:ghRfkBqLXovz36tYEczHKw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
