apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wH11MBGrR8CMb4TJE4s4Ntz5NaIJXwA+wjAPMzqcnRIMPwTz4MMiuvFQN+97TOLYR6+G2vCnIy/AtKFyH20DlOOS1909C1YxBdonl4abjJ47hyjDa6wYP7oIS2GHhCY5Hi4FwDPdgLXPNgGC0JfM67Uh7zJKzn1JGTXU4JUHvOJ0Vgje108w1We3XushqdcAFhElRYJrpXUMI5QTCNeyBiCjO2vG6SNzhj6vYND+vRqvZqbSfL+KJjKclSgFQUG+8EZrAu9E3WCFu790Yb4/E1R386rOrB5MGUVuOvzWIW4LolDh2hSDazZ4/69CznAyrRUEja7duTicno3GF5ua0rkDeM3zxx3P+w94Ns/Xx4AGsG6jx+yJtHNMUbO0bv9+,iv:goM+vlaPLKdDWaJVBFybAJmuh/aaV1RZuDDyN7qA+Kc=,tag:k+UqAanowYkdyotFoUwVuA==,type:str]
    identity.pub: ENC[AES256_GCM,data:qirYjBg0ypv632SSKpoE53eKfYe3oc66/MdMI7iG3HEU+nJJc0jKKsfpfwwpFr+Hrn+wY5MRJTkadLeATB/B5srh+fnzk/W5ajHNARjbehXAI8OFxB6HgqeKIEhKtvyqfGR5jF/Px4FZ47At/5GmfrlWERIIy1XT/slprPlZDXS9ICPCJa4+djmPTHTyakZSYicOZyqvep+XeWG8AERxXZXnh+4bUKbEacqnB4cpSOIqf/yKvf9gTcrMITKqqixvg+7rz+S5yLO1PN/eJw==,iv:DoXL39SnALZsQGDDz9I1THDGVmP+LcKDDdJuTt+yhWw=,tag:llVdyM2kzrUa/LEme0hV4A==,type:str]
    known_hosts: ENC[AES256_GCM,data:Pz2dpFohizMW0XZf8ZdPnJwj301SUORHiHaYDBirqkCPwuXmKY082+MR0C4d4iN1Zr88R47bMac/m5yCxWpmXssUt8hMzrXEghr+qus8NXQHaMKepR08r+l2y3zxT6VnHaEvfGIgq+dekAFPo3IngrbLAVO5psaL4Yx491izoVmeZnLHjJtgNFgCQDeqE8SIcyLcj3MmvC2tNUr9zYtFjvu6sasIJ6vFhUR2,iv:62M1+xnbazoxshIMg07krW5foMCYKw+5JXxjdzYfhlw=,tag:OrTA1vnRUMq74osgt+01hw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSEpOZUV0N2JQM0RJd1c1
            aitIQVRiL1hrbEF5K3lhL0RSRHFxL21rYUc0CjhZM2R5aFJBSGNXVDRCOWVYeXN4
            eCtaRGRxdGg2aUdIS0d4M1ZmcjFrNFkKLS0tIHJJQVZYMnBPRlNRVGhkZWlJOTlM
            L1p2YnZ1YXRlcldFN2xzRGtLN0oyT1kKVBQs3V2yV//wlbx7kfA8ZIjnNSaikHA4
            XazxoN28X1EKJRn+w7xzxAtUzo1g/GCfcdktMPNtSiuZdhSQdkKNPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-27T13:38:21Z"
    mac: ENC[AES256_GCM,data:O+eJkhdWyov2eDgj9YYmwseTkMsPlhabt/LtYAs5qe7Z7kwXZ8Gh+cEfwmdOT0W5ecap2I8d2LmX7frPZXeUC23qdbCkXP7TvyXtlN5JVNvgFE4HfV1yGR6XZJoJGypy9BAHIPFTgOEBSWKjfKtOyuJz5KdvwUIBNsLy0EJyHMY=,iv:zAGjDGxK9TM6oHK3nVfTtDjadq6bjGKsBfs0jpZxM7w=,tag:dz7gBGhjifOIxE0Jem8GuA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
