apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hSzCruLUgORNlHYVJ5nbF2+T4jQpKJH3T5B2sC+spjg+VfdFeYIcfpTv+EEMohwKgzPHQKOp6NNt+kdVzknoTAvMJfeAwY1BGVfOxsmnDot21T0lqG9jNrmTaHWWvsIgYRyW4a+lbxgoftZNOaG/0/jW3wyTs/zb/KwDtCw7+Kr9XNE6eN7v2AS0s4QjxnJvBNLAsqprkN8LppBZdNls2xvonp9Iq7QjuJuDjkZnirwR+B5Zbz09ak8JF6FNyFWLR9U9d0wC/ayxSMUsSAfxxXAWHBXb9vRGCdoBa901xyJtyJG+/QiIjGabLqG8MCzi8n47a9JfQp6xjJwiXY7le2aV+xv4rBzWlFl/igk9YF34fvbHlZfrSLJzHb5MrL5f,iv:dyLCRDN5yJiXDg/aQ8kyXNoEuolTRx+PtsPJ+bCdhlc=,tag:WxJY9joKFusefb7zbeXe1Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:ChqvZcfth+Pv6XQcc6G0OKO3VhlQpVGKpJsgZSh5vfF6dq5nv6+tmVs5DPBKZn/MaF0B6DAZXQBkDZar6ViphukpXguYPRpsb5hzLmpC4O+j674rnPJubStootCVg7gCk6i+KJvcoNvbcmhR7Gi1n9DwPYO+fvk5dKUPVEUOfUcLzx/LJSbz6/0KNd4CDOAexEkOfBY/ZuWxoTX7wnZUegoACe38WobOWzNJ5oz47c6EDGP8RIwWxOYOk+sEkXxM256er7LDacBiBoxORA==,iv:7E0lg4F/nGgC6cpBhEfSFDHMHHu7uHojZGXU8OJnq/M=,tag:AidgvP4kHAN4o4ZZ6vTpqw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Nn+fziN9EwVdIGOUE0V+iPdT6g//PMu/htznd6LTNesG5rxFVFJNDv3ybcuD22qgyZmXsEyHjbvZdg0GHJ22rrQqFAOrwLMYyS7vpb2lLb+NMtBNFDhlrXoQGrP+N8n4sXB5qvlt8UFcbCUzSlCtOd+DUjK56vr3V1NNS80zPO+QEoIXwtYt7najpC+DRwVp2bs2itwkTgz9nrZDtsQ/gxC3VBKF7E9HmJqr,iv:FjmQ+lbnKfxNVpQZ38EyYym51p/2dYMFnzmjx29aTnU=,tag:6MC7TvfxL/l79/bD6VW4HQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNFZUbWxQSEVaVk84ckFW
            SGo3QXgyaTlPeWNTYkVtZ2RENDh6Ris3VWlzCjU3dkNXTmFqcjdodVVvTFA2eCtn
            RVFrT2FJNDJVVnk0RzZXaURvUWNWaFUKLS0tIFlJNm9XQmwyTVNiTkF4TlIrZjBI
            OTFKN0J5bCtCUnYxRVpNN0hxMzFCVUEKH1JDklmIdkmkFlHfxzW47xhxejbs4UVk
            JJaJio8fios5IH90bkLSSfrsGc1GpUlyYktMA8abVT4dVZD+xu4HrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T10:06:41Z"
    mac: ENC[AES256_GCM,data:9E4BsEMlUMPvh3Wp+NMEUaknolPPkH+03JXs8tIaE/GlWDdNv4SjQlUmzXbdRmBByuijl7HrTvevf+MULN6+NXUBXj7vn7Or3I6q0XcjjtjWRSQ+yMWGIp0565JGTiNG8/br1J0pQosUp8b3hQHk2hVoTPrbRmwOQDGQsLFHxLk=,iv:W2ADfMspzPG3tBaOrThfIr7uc5d+XFZnqIp4LFW3zX4=,tag:XMBBT2bitEGT/PpCsFv9/A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
