apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
data:
    identity: ENC[AES256_GCM,data:D+U90A0h8y2Lpuz8cpYeS600XrHgyjDF/nBg5skrSAAgx7SQQ7IsdSaUhULT1co+D1m9lyYSxUTezTkK3OhV6XVPWNKFG/HSjsSLG+FupnKf8wMv9XO2cb5uqG2PmbSMNyGSfxwtWZ48KaXEYpxSs0WiqNJ8x9u3NXs93iRChWnvZSnTHCVUDUxMca5oq/Sd6J9KHhYjNBCs86mJL10qsIZH2Hxj5avTboOSenLHGAO7Bm4m2b+sY+NG1tsKdLpU9NPLie4hRRJw+O2FL2cnmphUmWkRkZdGBr10OssNWnTymqqw8ldf0qxx2/7MIbW9bPQ279IbWBEBj/A2si+PNcMCAcvW5UZY4D9bnX7sUy9uwC13Dda9eRNjjCpA+Rg+2N3FLh4tDBN5FefXMYyzKB/WkWMPE7f9eeHZLiEuSo0PYNfQOtmKs8HA5+V7UtdNWRrR56TDDQiLTyBa08PZ1sPwFE3zKKo+athuPAo1GP7R/w4AoA0dPqXNse5s4qFn7SrCEL53dZvXlO410cQqEkCbsIaYgKmm,iv:3WYZ8/PTZIKc38B/xvCxlvZYFDt/MEppRBk5bBuFr8M=,tag:r2TFgUTkrIWaChlJLtzh1g==,type:str]
    identity.pub: ENC[AES256_GCM,data:mXWMuwoZB8qRj7tiZJgjjMS3T8IItL8Mum/9uSvzbZO0aUt7sz/8D6Tqgs7yHuDPoJPaqJ4IZbvVYOnrzFtTqxDCe8fxcJJPLvKxPVtkca7S6cpwwGfgqsrTsmIT1F6r8WBZwwPg8q1dJv9dumgwvksgzhhrO8lzZjlZjpiJYFDb0Xgeo2mhoKopRCBcUBmMPawNEvLck7BTh9+sGVOAKu8+AayJc2IqB0V3fyuGwRFC+T42wKU7xrFqW+1yu4Kcl3ASwujL4sktx7b3ILJDN4u3TQCxHA05IVnUDABpyYIzZuJQpffS6mJwAgiTtojoTnybO6DxvjNq+Q/jkOQlHc7ONfJpcGGc7YwQfXXD10217I39,iv:vWiWruZMGVcndQCbTSuubpnkr/wNFR20gM+lVDhbjwE=,tag:xJl2qkztV9iQlCwCGLI2RA==,type:str]
    known_hosts: ENC[AES256_GCM,data:vwsI8t7eJcngqFyrgT7E+V71OR2ZPnK4y/GmZr/OgRUJbAdah+FvODH4JzlntmbDoZ0vfhB3HaFMev/Tms/9khbpm2M8jzXeICfZNbuAF7Ir2i9A1B0G7K44OpoDy4QFxxkShz0iicLsOsSQaglSMOtJVbz861Cp6FiGf2AS+eH/3ZXI74NmoT5LP2xL5FpddpVhVWJe647z4+XemeBbwqzG8s2YbssEv00zbIZxxS6/+e1NigZg4SgT6AQwRc2TX3/kazI6i98aJyJc9e5MwGj2ePhu/+9fpEkaDugBVTRf0FfY,iv:3hEqN5P7pP6dv5DGd8dDVkPzbqbsUrpZTWY1ZlJxSdY=,tag:jgfRRAqJDr+uGXQ5wA6uyA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTc3Y4eCtsYmphMUpOUW55
            anRBY2R0YllYSUdScUhEdXRKVEhLU0xjenhFClNLKzk2bGdvejRqZFVYQUx1L0xW
            SWgycVp5bjVxdUFKRXlDcXBnZVpkbjgKLS0tIGJ5aHlBSVZSOWJwWm41YmhhY0di
            OHR2OUpOemZTbk1Jayt4b0tZQnhSUzgKYK28SI68P6ywXp3T8NSKYwtnYZe+y4X6
            Z4bge8eD+PO8AgRIaRsWgLnXRz90fWurdSZeNbtUUHN16HjZDeooPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T14:12:06Z"
    mac: ENC[AES256_GCM,data:QHfqig8jQq1OPL3QyjFCYz9bBWN2Nb9Klew4xQNEERDFZMC6BsUBy3g46g3ylgvX6hBwwjcCRsG6VRhkm5uCIRUJ0Es5rO2nSQngf69v28h7JTvkqf9hKlhxo2wEXohKsi1V32AniSE2Wh1+FRVFGoqmBHk1mrB9T8fx5OGN334=,iv:2anhYOjHSZ9DO1FcZ2EhiufJRETFmUDiqhexFeUWfyA=,tag:PkxxeD5D4qeNheh7BtQ6kg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
