apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qY8oTTeZbuy17MxZdkcRrNYL5YgyUCfyTzQQ6GK2rrTy9Lt22McY2FTZpJ8aeY7FjU+pf1rn2bYeYcg3zV7+doIQh8kOz1/SSPogf/A8zJ9FwNrKzxAOKaDdFiIB6oubYyGZZFgYOyrTA9f4nhmpddIL/ySuRmf90gPhAuuzDYhim7W/sH2CwZR0JoHcGYST5bvIi5HYOBqIsJZOTi0yQoVTQlg6cGVBh8mlXMeb3Sb/BSm8lCajet3HYYBxP3yqyQA+bEHfo0ieWmZfQf0CiSkbDb6jGj5kpbx3mVABPCnVNLtNrVWCtg/Dz79+Gq0HmZvJC86WJ+NzCz8snhUNO7nJeLscaDyNJiT9OjL8pprSwkKF/UCGc/QE6Jcs93/g,iv:BHQAKlM37ONNiHLDLTAQAzgGRoJqSivbLd/LWyacKxw=,tag:lzVO3azqam54vmAEJHDSAA==,type:str]
    identity.pub: ENC[AES256_GCM,data:GWLTlj5Nw6qC+zarcCyE8GoNsEKDAsA0DeORcq3UL4Lw7QqxzFzylFFcaSuk1+Bf7JQwiHruQXM55qahk8gpOX+jWkYgk/zk+ylztqY321UaCs7lvePQtvT7I6L17Y6ln3vUtYMp5KXCmSt+JsWVXh5kW2gykHkF6rsazG5o2kL7EgyZ4VJ5vUFVm5Hj9RY7fRzLILKNYyithRk2FsYt+rqtjLOg4XEDcvIXF6XlkuOGjRWRPpsaCw02Kq1n05R1n77VU81SaqCYWHvJlA==,iv:hnehNiyDbdT4CxFW7nIlnDWHdnI9GJ9+EexG0+nEMoo=,tag:wh79h5c0Ohbmkc/KNJYIyg==,type:str]
    known_hosts: ENC[AES256_GCM,data:j74Gk/zQTC6u8B2HhK68e8qe1e5G3Khms5RmLMPv5bQjzbXVr3RMjrDgOCYjcENOeZTsmScPbg9Aux/BBJ8oRgY+XTmUyWt6iaIfkw4ccXezTVJq7ChWAoSJ34Rt43tBU+hKHPnCXec9zOJRvoYNBfGIwCL9qXi14rltu05oFTLX4+akahe9VqNOovMWqJEmOdXoa5UY0e/51AgBcd79HPHguyeufoPKLRVC,iv:3vsfrLW5o+pYi26djKSsE+qPT0UzcDgo2AAJG+fGw/E=,tag:dQ1WzimGInlnmNqRqw8nVQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZ1krSmRhMVJvWEpMeDEx
            c2tpaUF2d3pYakxmZkIwSUZrS05ueTZVa1JRCm1hR1RrQjhlYlVSWFBMenZpYzRR
            MjArdlF6b3gyR1c5OUZGSmErOTFXSFUKLS0tIG9DWWNtdFArMFRCVUZTYTRqSEhE
            eEo5azZzNDkrQkhwaW1MTDJUUFFxL1UKKVSVKDcKiOS1Y9vUaVfu8eym0J0bF185
            9UB5A8/Ei41o+LOstSfuNVpePR9Mu6lfXrqHooZV9S6cusPEbi7qYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-23T20:04:10Z"
    mac: ENC[AES256_GCM,data:HFvkWwB+zbCe0XZYx/Rf/uQDs3mEifAkI5P7cQctRzVLa1GOMECAjWQGsXdcWWRQxg6/r13HzwNFl52lO85BCiMzpe/S+0oqIJUWRnqcbqTbZjhMBSfycNEu3wvgMVPT0k7yPZcsUoWIoYckqXuZqKBz6kdXTvoVgKym1DDOjU8=,iv:LOme/gV1riAtpqFum8VCQ/5UkDCvEgh6uQ7HqBYkRCM=,tag:lJu+RXRXkeKvpFnd4/VTRA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
