apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:h1jVAx9eGkFm0WeUPW6ezikaJdmHXd3laIBtHlQz/HrXMjnDx7etLOguO6RgPg6n877V31icHOtON6wMiNB8mWfec2AyO7jxx3wQnfVPcnIHIMz8sOFbvrtHTQw648+mNK0Z3/UZsR6RgcPcH2gIVe967NlL/K6u6Mq5t/eLeEeNX2cBd3GPz0TCojNSm9WY1nYroowQtgCIENhafh5A9pG+Tn0OpdXKEQBtYm15VPWg/N9RV3MGWPkNZWRnTLRbWxrMZq4sgubA6gOi6ggqDWvfIZno/l/6IzeGifyriUywXxn/dE8vFLdisR4tbHncpGS7FOSaYvcdOEppXvvs7TUbj6405xmMq1eogln/6eJsnb4Hi0LJOcv/t3AQEPb0,iv:LzEKGnO08xl3qMcX9r4YaEMMXA1s6Ts9piCROfTU+N8=,tag:7NWTvHjMdDPU72sEpwkuVA==,type:str]
    identity.pub: ENC[AES256_GCM,data:I0hOoKChyOJP5aIiUV7gFX2EVaD7LCrXwxJlk0IGYpEcegZhFWRH1mwdhFsWtscX0XfckMgEBTEJDizslY0zfQDdSf+pHz/lmf0xyLS8YfCL4MVMsiNKcEeMbbZuWReUFf7eIXJZ++PGbgTjqzf2K6qqKUf62e7G1IBJmZfRsbaELvoYDiiWZuP/7Krm0lwztEHvuzyO8ayUmDJOHdkhbesVn1jXaSuPm9Ck5FOhTDIJDxv1ExldDwZT5+Q1d5XJLuGrSqYeAOT8xgJftw==,iv:bP57nLXPHgGAu+uqJF1g31IAVqX8bxKcBELCBGVcPxw=,tag:zRo4mOWBYoMJDCpMbikwYw==,type:str]
    known_hosts: ENC[AES256_GCM,data:K8zl5B7yYni6Jr6421BHu5Hui5W1otTJ/3YR59ch6eUV7YDu+exH0MYZixzaIwMCQL76GRBtVp5l+4GFTw8Ldn24EOvSuUfPGTbOVkQSDcj4MwCZUoo+CGScnFwl7YzGmbl9C2YmdUGKsX47B4m797pGG3rW60KM/c3QP1fe01p8okrjDQCTbK7NkwUSR82k0g/PcpR8DqvnAAFpswSNXmNxbsDfQsOACt8V,iv:vK3sUomrMqBhTTXrN15qmkk3mC4wABblwOoftiWRZLI=,tag://89hslcrcGEXJXQEwoMuQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicHY0a1k2OGZ4UnV0K2o4
            S1NLWTJoeEYxUys1T1hZVHJvcWk5aFNNNmcwCnMxc3d6M3dUNGtSS0NULzRZTEdu
            ZUNpdDJES2hBVGtscTQxL2kvbWlOSHMKLS0tIGp5bFdvR29TelVFZ3VzK08yNGdI
            dHQvS1FUd0lySFU3czJzYmtCMGt4cVEKS7VNF3oUP6PLoZ/fBXZF5qXMsyD+Kw9k
            8X1VpXl/BJoiqRh9GTkfBGA273SKLelWAu8awojzCJpVacrpvKgQIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-23T17:59:59Z"
    mac: ENC[AES256_GCM,data:h2y7x09d6GcXfFcFVhNhCHssD4Gk3CNRKfJfYM6p51XusV96eAVVem+i5TB55bwcSQq/iCl1e0bnHPI2AjJuj4sJC5sFkrYf2ukbtc74db87HTX6RkXwbzfipSWD6x1iyn1Atqw0qBGFGwfVd70J5qkHYprX4FlVwvvcxG0un4s=,iv:hvfuMmsTfRwJjnMwBatFtx8BGl0L9EKEke/pRg79H38=,tag:3AZ9QOJFtjnbfiFfa7/8LQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
