apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:282m3JuLRsS35QAfA1chHCFPwEaEsa+1mG0vXH8cCmRhWalIwM5qO/cL7a62LsHfKe9ie+X9NrMCN61KXswY+gJMuhlUfLK2xBtWVO5YxyFp+v/rxF4mO2n0TtjsaPhsrek6Esvw9MDX5bCk3b0i8fk6+2oX3bn0GgR497EwGAtj+hSokR1E4axHhO4NUimnXSDxsPHOVZH+XojR3TaieSAc35wwiiiYchh26tQErILDqdJLBhPHAIzksWuHvPfOtreFXqxmj07g5PRaJ1iFkCLcDkJOKhaZ9aDL7t7yaZ+0NiMhaV4vOLt6O2/wDZ6c5SeqkD76wOzNY+M7Ez16MKZm/naks1JxpgSiG03H3oGixryHoL/crCq4HD6cX5M/,iv:IvdWHCj2wukfkdnE35jQMpoWMKYhBDqmrO5Tl30aQ+Y=,tag:qxwrLbKmhTTx7uUPsX9xsA==,type:str]
    identity.pub: ENC[AES256_GCM,data:5jnSDwfAL2V1rH878XkdMfydzufv/BOO2/qS0deFXJ+aMr3pxmJcKUWdkefXmtkhIs3QsriZqtwSqMkL/A5VexKSLI1h09KnRQGRRnxFADhg0E5izTmwL4B5xUvtMiI6WR+JyL5ibOPqCm5GmOrkduNYK8A6WenwUfVUIyWtAQV30IEQ3Xw/diYF7WMzIFe2s6xvUJtFWI20vehYzrQ5Uuxx3wQXNrkhEjYUPKAYItCIfQElB7MNYefZOn7yaC2KiutPgb5i/UH58huEjA==,iv:9Xf1o7sa8sbGKXaG3mucR4ybbTXSrK2jHLhJNVm7IGk=,tag:hIUwiTHaekmgooYBPkESmw==,type:str]
    known_hosts: ENC[AES256_GCM,data:ToOeTDh3CzU45eKaRvw1Jb1qbzkTxxXliSQwU3Rd+3tsF02PFe/we2hZMjgojC4WFhK47Lf3pMuCfGewKj4kS7LWtKbVDwij9vgV2UTk+78m1R5GbQ6sM5td4ItKqu5XNTTjzDJXNwPFuJ7gxx84kB+NmbgDx2ViwLLpOCszQsLPD9DeMB60qXQypXF21zLIS6FAtZvGyoZ+CLHAIpsOLOmC4Brv76/Wfm0/,iv:JHJjWMmPHMhoIfr1kggrfnyWbddYpx6BFbtjzxVWTEE=,tag:AHHWwhqa4RuDmVk6wLaNAA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZR2tYNGtaL0pBN0plUFZ4
            ZGhheStNTThEcklEK0Y2TDYxOGp5MS9ZalVzCkQvakhuNVliSTFhVHBIZFd4bVU5
            d3o1Y0ZQKzd3Qlc2dy8vcHBvRzBlK2sKLS0tIG5vRXpPNGx4Y2huR1FNOEVweVpM
            QncrZWM2bE9XLzdLb2t2N3Vya1JOMGsKQRN3Y3UQfCoEUtpNy+ZPUK8wXoFFqUYP
            UcaEryLlbJP+lOfMPOPhVNfivKI1QwkS9Enbg27/IuI0CxKhqdOmdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-19T22:07:13Z"
    mac: ENC[AES256_GCM,data:k+rt4XxqCQBSzxZFG3wfvU6qYcegW8wpERe89seaqeVPVrwcFZxWWRPKhst4+Lr4fhmMJl+hNTyAgkq9iEYsst/ezR78uZBKdHBtpw8jahCoYF6qs/nUus3qKMzd9MpZLjHwIl3UFYOLzx6s33NkHSnUOYYR2oSpIICabqjCndQ=,iv:2fXEq3xSLuG4bcO/UmBcsyQWR0ZngFvyKV+wTnRihts=,tag:xUDNeMcxTvC3ZKA+Iun0fQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
