apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:roPjj/bmv7O5E6fizIIInrVNqLDS+Tr98C4ADqJBtD/IGxiK+ahAB6+noBD3t/pC/LgFYkUoz+4EitoYpfJvVhm5b5OdEN8cCv97bpNx84I8JpNOSvLl5e8qYY6usrZm9HYztTuTpPszDcUQhgy1RVxgTEm8dXoNBpE3FvBLt2gtbGJs107Yt8P1N3e4CuYGCioLzHQTadTg2siahDJxBJ6ZqoeQDtoXjA+nr8PAqkgOdAmXHy3QQGilz/wiHP2KOqqsBn1WQ1bQfIhs9hXq//6dhnhNUHHIF+tqQtUu96/m6GIk2IFSjSOVHORgeKmHRQ0IucoyUIq2IQVLsORoUsOaEUEY+MAoeYfp7vvsREolOY6k0F6g1Ms2P85QCmq2,iv:WHCSZ0l0Xzz6EqnxBEODuQQU5P/dIdC2gDl4M7Pj/x0=,tag:uK7nAccf8XucoDkpw6AgKw==,type:str]
    identity.pub: ENC[AES256_GCM,data:GvEErDC6yvA1HPimX1DejzbNa5qEuzXRJECO7v/bYXQDjjz6MqhcfUkQ3m2X9TQotfaDHK/AiVcSt0rvzVzKKQl9+Labhwrb3Vhl1+r6k8xkOYRWoTnq9smq/1oWFHuiBPYlO99kPK80U4xAlF3A69xGRcDNQizSLDAQ889HlKH5EJI98bf8B/4MhxewvtFLBDexjKkhW1TKbG1uyd6QGzu5nf3paTChiOKF+rM/BMDHsHOGiogKsotAwaD71UHKB9iWQHEVx91SkaWt1Q==,iv:k9o5Afuqc3dRO/8gfKNS7DOOOAgYphIMEvQqEQJZpDk=,tag:TBKpuybl/i9osBrCv7M70A==,type:str]
    known_hosts: ENC[AES256_GCM,data:4SZadCqYvJztv4hEapK30esEbT2MaG6ubg1AqbTqPFeRtRSza9c6QjweDrftgftKsjwW3RlCjuXaMn4EkiSZhERQulRYALqocY8i019OdmpddSahQo2G4lQb57nO1NZ3jOlHVJ5lWEa1ZFpOaBosa8w1YHGiHnT3aQx/RwNuNVkuZe7Rc4WaT6ayH4Mj3GCl7k/wjm4tMWVj4FW+4EJDyDIXM3D7Cx8NW3pc,iv:AB3Pf5SEaa+4aQ3VbHREuuec/XcfY2v6m5xfmoc+CFA=,tag:l5Jl6BInEYut8Ib+FAyzFA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcytYOWZMV0tiNFhqQ0x4
            VHpsaENUOUF4SWxTMXE2NVdZcGtJQ0JoSEJBCnlHNUhwcDI3elNlQmRHbGpWM2pV
            Z0tJLzZsZHpqRmNoWTlZbWNVR3FxYlkKLS0tIGVOM0c1a2dhd2lHcWlIV0tEZnha
            VURlT2tZYnYzcTI4T3BnZ283ZjFFdncKIuOASlLuJ+DVl8EwvtduKQ14CqRUWXTz
            xg5HWZ6nvHMCivSFCYh7h/UF1U8KzQqTIJsyRwZpaUMbAmnq64YCfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-10T15:49:06Z"
    mac: ENC[AES256_GCM,data:8f/J09+0DW2VDOJA4qCaQ1cfdBAeFOPIzKvWsnzxUFQxWLG4qS2k+u+V6VA1I71+XDhu9T9npYtJCP9w8kGCJ4sTfsINAlAnPx6++dnOK0DniuzdhBQj42ZJUJrKhd0W3tk0E3IjoEXsBQrh+PDElBJ1+iOFRldBdldTF6P4FoY=,iv:TRgL4EmnLbIZwyuRKY1GGCdPAqEPhCCU+0eDHFZCBgg=,tag:4iOuCLvdR26JW+8xsA2f9w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
