apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
data:
    identity: ENC[AES256_GCM,data:d8CJrznd46yHsFfPo6dv/6Fkkn2/0za6JdLHoyQHDd70aNx8cFx7SJlYA2uepSU0/6IhJqScnndSQKDPyk+tltgYf0RPCKF6x1CobsgWTemwR3l8NmHmfqtawJPOIr6AxnDKcUQoIO56Yan8O03cHshiCK4V0r4AeXtmNk6kQxb3qwfrZiMdC/xRR1iV7PAZTYz4KTbsXheXDKuHyShH/vHBOUd0HTdVVoXj2F2wz/9SRyusE0iOImIzPy2anwIX1aqM90ZTeeOHm4eY0CUOrIUYjoFmHpC05xZUQ0pT3ijYZUQZgY2d2PY4WmNV/2hvqCgomGvEfPKqzDf54zq2eOm5UNeof0gFHlnPAMcccJjPptGd+CxHLhDqhSWljCdGw3mVx1eNvTRSIYIryC1oFc9hoXy4ur7xGcD73KfA65bXqTn0YJ5K7eRWeH/C+1b8Y7IvB+p1+P5We2XKbWjNt9WtFcHt8F3tiUM8vH0yoVqIVIPf9mRe8DNA/Iz6qqyquwa48adQinOTexetEAA4aQ/3jpBDsFOF,iv:wlNtsxxUmwE90aBcy6Z6rXuPj/GqI/PY0HoIlr+C3jo=,tag:pppMMbv8GcABdNYhqgKZ6g==,type:str]
    identity.pub: ENC[AES256_GCM,data:6keb4nM/dnx/qj9f++PbYu+oQlpQw6D+ZoXqrMHZXgjerhaSytMZO0w0Ws78rX8/23s4HVJV4zHAunlu9CcrHanPn4WKA3A3anF8fdQ0PkOXmjFLKCkb6NgSAXYZYtLPpVtPH/oUFmwWRDmR+NsCPNcS7aPXxAILCbk43CD1b8g7bgFCmEvyqx0A+zghBAdFbUXQowJhJRulvZq2rAKUOJDVZlg6eeVCJsElVCjlJ8OKD397wlw8wdHhjefFxM5FFQMa7gRdgTU3tNV1IrwdlZQYYbJaOE8qYruHcxB5KmqxIR2/1MUrzAqD7tSLjgemWScs/4wunGzK/Pd0rwUB1zlzEWMJ0SL4TH2KgqPU74D62uzl,iv:rrrj6BrrEkKNLZykmknXcl/16oOZnQsd6DW+LZgqKPA=,tag:3QAGlGBz2Jacv2uUynhkEg==,type:str]
    known_hosts: ENC[AES256_GCM,data:kTh83EXnguSdOKaUaIe3IzRGrckAeI82awNrh2q2dDZc0n8cU0Z2bCxZhvBH1owfMytu7zecSI+/ovZyXkp/KbQYIV6Pnn6Q7/Xr6AsJy8p2cSe5nGcjITEkemP22Y7gLU5uCzUzQwgJGs7vOD5Ua8rF/2ijYc8OzqUjoO29UpAIpVS3ILLKTLtLExYHCd1irSDTuttPReoJqJ7NnOhBd25/objSA29kwDEGtxYc49T5CjS8Y6xCZOREFbFKFKXgYGzz9UrR31R5vaI1qJ+0n3gIFAUwWwOAE/ypMvoVU2J75lit,iv:Bcb7DRNYCX3C3V2bfYEY0fJ9s48E8+Kp/Oufy612LYA=,tag:jJEV5AoM1LNkclgR2q1cRw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTmFLSkxzVTZSRmQ5Y285
            UFoySkZOUXBJOGhqbUUxcUpvZXBhNHhNMEdBCnIxSmk4WlYxVXZkM0NVWnRSaUNa
            Sm9tN0J4TE5wZ1RHQklscXJ0dnhwRUkKLS0tIHladmxJZjJLT1JIeXJTWi9adm1l
            UVNoV3ZuOFZXNTdlWU1GZ25lTGRxZ00KQAdVuaNs7tFdoPx0kqmmfuVA+XW/n6Cr
            U7tYMompWKQSPhP82A0mY89aMtUsLzhgh/U8QDyA5xA493gI7G50Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T12:48:20Z"
    mac: ENC[AES256_GCM,data:xFqVUsWW3IDSGxQELcdnw63yUX7g0T+JU+w72wYPvR8/pdjXbT0yrz02qI2OMzC1cjSX3FsAwkemYXrXIuEP5Yo33F6Xf72FddK2P0JaqFLYrcqq0v/Eqlps/oBy38ZyCiFLitn9vTmmuDh7dOfLkUjRjMdojc3A8AiI2G1hnLY=,iv:vnRqKpTBeVlfgPXbWRixv0zfo76CoxJxig/TgEqN0Ro=,tag:jwzGMCTDd3oMoEcTt4uFGg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
