apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
data:
    identity: ENC[AES256_GCM,data:asIyZIznCcRJWq+ZiN8r8H6FgQEiOZaA++DOfKJgSpuNUV0PnmDy8W1NJcc7+NDMjVtiJxTmkGEcYBahdmNsvAUdB+LnOJvs1lbBnmzC+vwSGq2J9UkgE5CecOUcopE4/BHQuIzhd5rVz2WHVwHs94wrsmzX6ydJTxT4WOk78vkc7IyParOda8noLR0smngbRwWpBC+ovY5qs/Yw8XYNSwjyyLENbyjwZXqDe9wj69ZRiu8nY22iZ6qroYJro3THUvlNUfrQQfZm9GuJqu4/IAUZ9kLZi4aJXyJmEzrODalif1p3czU/05c7vbA6LjrRVGOE1AQLbWpBg+QXxVX+qsCqWsJ775ifxKiOyFx+WqwGTcwr91zQPhzyfqacKSxZFf/G9PtZGy6HzI28agOOY/970orMSS+pxAPvxJRcUgtSxngZpZjPmIkV0bS62YpoL2Dg50ypVa3IgfkXSBniDZfK8GP3LtlCsuj3mKJNIn/fO3KXeMN5SjEeKbG4JFt1D7t2y0BoMxnCUnbO2TLat0PSOWpW4CiZ,iv:pPVFY9hdXhlqGs2Kgb/cVYmPdjDbvZi4e9kCjj1FlcQ=,tag:af3SyndBmWzAte/8DvydNw==,type:str]
    identity.pub: ENC[AES256_GCM,data:l10lh+Vs7e0j8bZYSJ/J0NoZcD+BdJuif6YsntTorLSkxa8hpoM5QMK9OWMJDY4MO9BODtpXdySfKJ0NU9JoMO7nlYw2Fliy5HGDI9PHT/rPWvt4U0oXMyYQZ2GShp28Q+wRMa+ZmoI3uojVuKh0a+vjfNML8E9PFAskS61997mcTonsH2H0jzPW4S+nXBWYhlY9aJGIWxYF8HvZNkNdoRY2SxPXhFTZLgal4ALcWQlz+W/k+Rs1+274wDlokoeaGuJOKVScEGLMKN15IFBmWuBeQUB9yWiMCX6nipWCQdVcTgp/Z19mY6+qfsr3y0bdExgnG5yx7TG7+XHmc+1niICxybbH+fsCycJBT5E/KEjHECUy,iv:bOCLE/yoL6VdUmosF977GyJtmH4hcHjbW4i2AywFgdo=,tag:hc16PSJLmYv0Cq9emjbY+A==,type:str]
    known_hosts: ENC[AES256_GCM,data:iNStdDL6qdT3YEMlsuAU2FZaFepyl7DRwXeDQphMKl5M69lRZibtyCFqMgQ2rSOpso7Cp1TLgWSTGN1Ha9M1tBgv9mnYhmZGnNieOZuV6Q/3O/ruLjb0FWwccvDZZnwn3eOu0rQY/hDUsseQdcqfxi0BeXHiGzDDmm/QICzLF8xeViaUnkgeTqMQqgI6HQpAG38p+LNayGtd12ZpRl/KeICEqdXO9kKnw+LFvCpwkHKXzV1h42M61j9vDwdreUdfIo5IqlfjpRe9eLjNsbFEJVzTPq/KgkQewo2X1nPoeuRhdfpX,iv:FM2cqmx+XkJAvgiMqMxQ+gu9f+7dqMP4iB2/yVvmNvk=,tag:eIbCuCoSd7o8pVpeuk7oiA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSEdPRVB1NEZhVlZJd3hH
            Y0ZkSjJoM2x0K2VVZlVaU1JkcVhXbVJsOFFzCjRILzBGZFZzQm1Fb1dxMHpZQTdO
            YmhjOVRZendrS2R2TFdGcjhMS0NtSjgKLS0tIHh4RUZ3ZmR4Y0o1N2ZGTlZPSGRW
            aHpRU2d1STlMaUt4anB6WlhxRGtTRVkKOFj+TykOOncnqGlGGAIioDEexoiAuK0t
            3zil5pj8gqEWOfyPcbNtAT0hWKpcDLDSL2bD/+/GJALHLhFRX1woPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T21:38:36Z"
    mac: ENC[AES256_GCM,data:gfqi4+r0t0Q4S1paiUEyNZ1/WHitU7TZx6XNGyQHiDM9ubGqu46NwGPk348Ip+hTmXkZ44XnBq+N8bQGtCZrDr7HL8A4Ddw3OUE24Wc8QVTGLAn+3hhmazT+zZ3hupq9YsmJ9Gmh1+1/ltykdoNtwxKWeHsMTFSBRhBjNW7Z5kI=,iv:FafA0+5rSDlnQRIBrFtc5S8VAvUu5bvTh2XEXpogkqw=,tag:8GqLVh4EXgu4hlN/CnONSQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
