apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
data:
    identity: ENC[AES256_GCM,data:Nz0+GoBzwWnb18ePkE2b2Oub1Ia/ccavIswynrA6Eb0MVQSC9XmaVnRI66qYGnaHQ4HWEOObWoGyFYPH4vnmfvOTtsmpn9l51aHFqOiC9+68eHB+kWadzA/GYKqXg4ppNGPrybMb/NTBEzy7KBDgqG9ueli29n39skfQ/hFBSpaqrzLjC1Af0FjXLzYchrv9bLftjkvZ119uu8sD013p2RjCJ1ZNMlLdt7jjoXzxTTKybBrpzE8bH3dosBkvO5XHi9IPLzebVPGd3+w+5fZ9PDgPBG9r1hbGAHpM5Isge2Ubtg9nEjTh0rr7jiJWO+8fASARTA8R8kDWIE5apwm3ziHLRC+zK5YSVtIqyUYBdMxfjTStkqYj7rxIzGJhiCvwithPvjaH9BsNtIXLNhalBl7Hu6DpRiFudJ8vnvvTYkhL07mA0jfk8j+jft9Z4FJXvTqwkweulxRBcAhbhVoMlXo8Lwxw3P18NgiBZFkI2rA443OaPwo10bkKzad2672VJeF/q4DxL7ojWii+jzy/+wmJdE7bA0FW,iv:9pI+XD01qtc4LUMvZQSKHtubmr8QSBF2QJTLAVpIdDk=,tag:ltxiLgk7MeTigJJeBkQAJg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Tc3lp+uct96opVGafjP770Re8x9C0Pjrlhy8XYDr6yLOvtO2uvUlgUc+ur2vu9uOmKtI3kxH/XlZzMSL/5CBgJurONrrHPLVAw9Qz+mMuU9OaTZrwOMHer/UblSA4AH6jPpcfz5bKXV8YyNrcs4KeLkO8beYxjruRT2ECzlOL0jlYVd6FWYqihrFNCxvrdSAq5xvyl98kvnk9kWaxK2wNWEB2yPjaRDG3r5otlhJ3DoYAQs1piwMv2eIqopZ7bhJSTpxPNXh1NxVZNZAZyMl0FPEVRJILSVVd+CGOa46Bf1SSjNQZLaCIOvB95R70Kl15X2Ncw+A7KP9Eu5ThQ47mwWFCxGvM5J1RPyEtHs48n5hYI1H,iv:C2itzYe0BxTSfk2atgwyWNcR8XmcSa43y/Sv58w/u5s=,tag:xrsORJrcyWhyjqWViRGihg==,type:str]
    known_hosts: ENC[AES256_GCM,data:BZrHB8zD56rc4ICDHLi56J3W7Im53fZd6IW5yYj87WYddI6tp9p0TBYhwgzeMMQ2K1JdTqkHzxPqXY35eu9G0f9vTkVEp5nyVM+zxSYFn7BImXFiZ/l99EKxOOEzCAULt5cmTwH9Hk5yR52SKWjxd1YNRxJ+CFWGeDYPA05xqAYPj3WHXMPw23/b++wpxmZqi2mn/ns4djvOr+pmzFk4SL8OILp/mA4PVab3B9JwsiEuLwmBcSRUWtWRB/fO+WjmPE1AUscQ/1jFxptMaHhcEzjrkcgOOkEpoziCwiqwiqnzZNeN,iv:j7T1p7uA7uyN+Xux/vZSI7yxkwFV6VLnj1LrAT7xL4s=,tag:Xdvd+yHLK70OXGhno4JJVQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSenQ1b2lYaVdpOTZiaE5x
            YTVjZ0hYUmZsME5VVWZtNk1kc3hjcUVEU1ZnCmNuVG44UnF0ckdwaUQ2VU9tR0x3
            U3JPeXpyNGkzVlBTcGNCL1VRZEFLRHMKLS0tIHpvRzBwUUw5a3EwTGk5R1pFVk5E
            VEtCVUY1YUdXOTN5ZlduVnAzN2JyVEkK75nkv94CMEqLlMrY16hR9+NNWZS39cYn
            E1uoZGp7DPqu3KAbuurcCnaicMdV+5IuP8A1GaP6ma0yJFebu/U2dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T11:07:13Z"
    mac: ENC[AES256_GCM,data:qmqMquEbYDOAVAuPeHhtkl/1wIxtK9dMi1hP0IjQ9ohRRDlmaFbLpqMesMdH6SIVBD/hsEIKUNS+evevjg8TH0K3Fc6J2pKfca+FFP1vowUGEjJ4bt2QirDYbZgfBuWkJ9/97xhNC37EI7lhuF6q2qC7e/4pLkVYnlDeSKftcKo=,iv:Zi/Htc2xsj6PjqmjR8WoZ+f20qyyOaJm1LCJzKGqZes=,tag:qw8iYd0SmBC/bvz1jFXJFA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
