---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hass
  namespace: hass
spec:
  interval: 15m
  chart:
    spec:
      chart: home-assistant
      version: 27.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        loadBalancerIP: ${HASS_IP}
        type: LoadBalancer
        annotations:
          "lbipam.cilium.io/ips": ${HASS_IP}
        ports:
          colot:
            enabled: true
            protocol: udp
            port: 5683
            targetPort: 5683
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-hass"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"

    homeassistant:
      trusted_proxies:
        - 172.16.0.0/16
        - 172.17.0.0/16
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          traefik:
            enabled: false

          certManager:
            enabled: true
            certificateIssuer: le-prod
        hosts:
          - host: hass.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix

    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
      backup:
        enabled: true
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
        mountPath: /config/backups
    secret:
      bearertoken:
        enabled: true
        data:
          token: "${HASS_TOKEN}"

    metrics:
      main:
        enabled: true
        endpoints:
          - port: main
            path: /api/prometheus
            bearerTokenSecret:
              name: hass-home-assistant-bearertoken
              key: token
            
    cnpg:
      main:
        annotations:
          cnpg.io/skipEmptyWalArchiveCheck: "true"
        mode: recovery
        cluster:
          storage:
            size: "256Gi"
          walStorage:
            size: "256Gi"
        backups:
          enabled: true
          credentials: s3
        recovery:
          enabled: true
          credentials: s3
