---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hass
  namespace: hass
spec:
  interval: 15m
  chart:
    spec:
      chart: home-assistant
      version: 27.2.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        loadBalancerIP: ${HASS_IP}
        type: LoadBalancer
        ports:
          colot:
            enabled: true
            protocol: udp
            port: 5683
            targetPort: 5683
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-hass"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"

    homeassistant:
      trusted_proxies:
        - 172.16.0.0/16
        - 172.17.0.0/16
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik

          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: hass.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix

    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
      backup:
        enabled: true
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
        mountPath: /config/backups

    cnpg:
      main:
        backups:
          enabled: true
          credentials: s3
        recovery:
          method: object_store
          credentials: s3
