# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-small
    namespace: actions-runners
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set
            version: 0.9.3
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            strategy: rollback
            retries: 3
    dependsOn:
        - name: actions-runner-controller
          namespace: actions-runner-controller
    values:
        nameOverride: ENC[AES256_GCM,data:1BbajUwIznXOq/lnddmTsPnBtt36,iv:yAkmjptf3Q55jS1ATmmYsY0QZK2fCuVVARqF2P9yjgQ=,tag:NOtmGT2ZVfp3WtA6lKFb/Q==,type:str]
        runnerScaleSetName: ENC[AES256_GCM,data:aww2G3IPEyILZ+f9W3dt/3NsTtvn,iv:UwHN90OKjy+aJGS+ePkfdHcJy8QMsqSQmcNO+6swhq8=,tag:xDjANLmva7aWeGr8PLr/4g==,type:str]
        minRunners: 2
        maxRunners: 6
        containerMode:
            type: dind
        githubConfigSecret:
            github_app_id: ENC[AES256_GCM,data:r1zGWF2NdPn1VqGMT1hDOIii8dDVyEUjAMQsjya1EGbafuIUxL/urg0=,iv:XO+tCfGR3kfnZrHw/tHQGsxgomqAGpWcIX9Bsc4TfGU=,tag:4+UKZo4/6FMU4pDWv2KKzQ==,type:str]
            github_app_installation_id: ENC[AES256_GCM,data:IDl6LFVCcOQ=,iv:pljKlfJhG5QTPNRNUUm8rehehM4GtPyYeFCBDsBeBmI=,tag:Ajp62BvAy2EjFzE14N7MBQ==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:qAWjL5T+CquZZak0sC+C4NYSPqry4pX7yPgdwlKk4DUhrV7NpqjFimnSH9Mq8dbEpeLIjHNWiAD67JhLwdtpOi7q1ewLaqKcipcQaEuYxvaJw2ThDAOKYS+Fl77vny6lwNwVNYxT2ts1rU0idRiOaozUbVkPNd/t/pXkzNNiMiReznPb9IWEEeIaVPbpbvRwXu+q0CvcT3Aj0keHnQuawr5y7eXcwaYZcQGbRbSEe407RDeB32Gk5Ci+T8HsYqp86Gg/GmI3//HmZP724X1WpGTKd0eQHFYCfHvyFkhxHidoAdiVI8vMNTI2ZMDt5rHwjYvj3q61mwvlB4O03YF0DmOCb91LNhGZ/xtYR0yIXjn8Lfq6D+nIqMhZVLmqYCbHujnS/FNHCggJSHa+KXXr4xRJ1YUUd9JfO2ym4TgwZ5cOx+q1P2D9p3Lek2b7kA4B2U676mKRxXWLQKrRl61A1WVNDJ534NyrRoWg+9Q0/03ZysqBX5rxL5D02moirbMAbyJsFfvuDOiOJ86ZFxIUIsx385vgGYdH9phgvTYaTTPLrGffWPvsZ6Ey2b6XJTTCJYG4rhja8EaBrwyUjdcTXsEVeKZh3i4FDfQ7lP7w9AW9XuC6a8PzR0yP0rFUzH6FjWNa4LHz56RJ0OGNjEn6mGocCT8INipuoe4xGbtPL8wqT2cxj3+dyjQSFeppXxsFc8XPNLptYUZSjLo9kraFEOHQDM3+EuVIga+gbcE+gnP2k/BNQHuaLLcmNAG9Dk40hammHeLySSnbFsjKFhYtH+bHkIeMqjTPx2B2/TG8BwZw03QoBlcUjyun9EsvIAHsDyJxFpH1h/V/gkPJN4rHMd9A18lrteA2c1NapQ0tPmW1B6kxihhdi/iiWRMrAJsKOMWjSZFNdB1RW7Y2/Z1o7NKyZwc9sfKjaBEwXdhWZr29j8ELDQwPi9KMzBonDqUtAT3R3WX26JmfEJsfaRMkJNpXBggojc9DpgfCNBhS9I138xwAaFwQzkm00z5R9zSO+URqlL6ypcRzxeRl5jyXDb4RgtCp145zhQ+VplmlhY05aHU5xmVHdfDYDiu8TZSqpM2Ijb/mjCOmoh6L8p02n/nZ+PFSm6Dn7z2jogiBLw5YDItlPHmWBOTrkWV9PGjZEhvW8f+S70iUn0L66OuETDOPpEa2+F2jJ6Q27BOmCd2i6oqbi3W44YB6SeASxmXGAHF/SmE/HkpamU6i6MO/RDHEFBghxI+QSMulxHGDUMPLFnIRqqbYucYJPV2d2ig4fA+B9l/X7RYM36aanxw8UIQP9wjN3+xbuVYkCo/PCM73xNdjZpKV0McfsbC6eaDyBHSA5aIB2gNGGXHFIJOrluX7tu0CzTbsr3nN1rpDWAH79bREv17jEEtZkGjrQT5peR58d2F6In5jNSmoRzRJ9W76/blnljcwcQP8KIht8P6sB4HWuDF+d5EKMUbz0PIsQlTASORg9ZIS60KL/8c6IFmg3r4qkTMQbAPnmquR14szSfIMLz/kn2qmNwaIJgw6F5spUPNrf3t+/Eqc44iAs5YkkX3lE5aHO/R//1AsTfnQk2bznv01vQz5MiMEDzZCb/qwVUm6AFKwmmqg20az4pI/uE1CjYnEZuSZlkzaRFaif8dTgYDRPDLpGLBQ7DufQGgEEEYnDA9TsDzgZ2QTRQPqXiHxql7meS5B4ew9GtqCgzeH52s4E/Vb07DPYpStDTMF6Z+v/qwGijFa5gRNnSdxvlV2175YPMvoKSYIo1Q4x2U8V7y8vHaMV+0qb64gYJeSypiy9pvZ0Uhnj6uKCgSypQyva1PGUFl5BZl0tdBMX2expMrjcUsVZ+sYvkaH3lpWE3ezo2IV1Q9IaAsdnddxzvtfYYKHNZ3QOh9S6J1upaKcSzVcJo/4qA/oeciHSZpEOgPdUbsD5QizZ3B/jaoy5/7KBv6ScrawfARKnA/Sf9ykh8wd4MD1iuTLM31T7RO5jzRntIIkpVDcVhps3La1ZTMDT5cpYfp3SZ/dh/s9IgJbInUoGXwOmqoHY+otJmaBsi8bSNg2HmUOczKeA029K43MjBjODC63X824zMMp1wM3JXpqpva2eSR+nB6ijrjB2nNQmFtof2Y6aOJ7W49+TtapqvMNngTqU+X03KYJZqSEDvuncylia1K09pJliG7EmJJvnT1oN7x1b4y0dbrgq+/VhtPCRtqNMZ3wlJZqy85vFpWO99WKXQ==,iv:f5Zg763mxhcTLwp9MGsS6l13oDDMhSwjuaDFyNeiMPQ=,tag:U5I1++R9hNRR1VgeLgXzKg==,type:str]
        githubConfigUrl: https://github.com/truecharts
        controllerServiceAccount:
            name: actions-runner-controller
            namespace: actions-runner-controller
        template:
            spec:
                containers:
                    - name: runner
                      image: ghcr.io/truecharts/charts-ci:latest@sha256:7541472ba15b8488c54651ef028cbfc286d9a0c72fc066500ae2c6cef60ba84b
                      command:
                        - /home/runner/run.sh
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSjF6aEVzeThWNlIrQk0x
            NFoySTdBdktCYXhQdlNJTUdsc2lETU81QUFvClFoY0gyczJ5bFYyaDZGOUcxRW9I
            T1lUelF1eDhOa0pVK1FPSHRDTlMxUG8KLS0tIGNCNVlhbzVVUVVuRXoybHVEYjIr
            cEpyODBheTFqTmtvSUdWRmhlaTd0MUUKr2/Zuj4+oHszOAFA3frJyRHiQuuMCLfI
            N2W8LSdjfWd3huIpyjCztzKPElt1fkJvsJRFVlfn3sqG6YlzKOj6jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T21:34:48Z"
    mac: ENC[AES256_GCM,data:a7M+HBGfqeCTnrS29N4XJwE0Ss+H1epEreBmHNADw8cC6d8hQA5KqiIaCYHtieB3xKrHct2vFK3HxywJMhMAwnN2eA3wGyhzSKw5C1pSgjyYMB0m9FQ3bK7K8e99qfzo9YE8XViazVEyEXR6k/RM2xRSUnvWCD6MYpowjrOAc7s=,iv:3hXD7iwKcMmYfNIOtwrSriCN7tYVfPer9Ek62fhHQLk=,tag:NO0f+dyK9vQ+S9tgImJFVg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
