# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-small
    namespace: actions-runners
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set
            version: 0.9.3
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            strategy: rollback
            retries: 3
    dependsOn:
        - name: actions-runner-controller
          namespace: actions-runner-controller
    values:
        runnerGroup: medium
        nameOverride: ENC[AES256_GCM,data:Rrc16Mm4omuROOCYaiw6tina6BTN,iv:JnIJQt5oUf2oC/KlbuBf5GZoBdu93H9wf9UlZRPkLMk=,tag:NdHPSJlqCax9Vnay93Nh9Q==,type:str]
        runnerScaleSetName: ENC[AES256_GCM,data:x9cJ4ByqRgFrqUf0/r/qYd628ShH,iv:ah2bAKF4h79126hLeH7AqCR6uEc4T5b+tVGlVKU8TRA=,tag:ZqTKhK0ETtk7+3wnvD48uA==,type:str]
        minRunners: 2
        maxRunners: 6
        containerMode:
            type: dind
        githubConfigSecret:
            github_app_id: ENC[AES256_GCM,data:dhSN/yLnaGze5MU9sf6l83PTtVxwdBN0+RoKWvO2NtFPaJxA8NegXUY=,iv:vBCqy4+ETDpJBDArd90Jvj9+CeXUZEyRnLLKWWZUZ+0=,tag:z1+Ww1j7pvxzHG3yE1Ozng==,type:str]
            github_app_installation_id: ENC[AES256_GCM,data:12ytKcyhcNE=,iv:QQGUkpIyLKdp8t1gr5I3LPR3yzvAlvHcvS5xiMUWJG0=,tag:3um0LHvD5cOCMTKF760ZSw==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:5sHB2TAj5siAnxocq4NKDoEeTjRxaNPav/DK+JA/1tGeDfpMSWYhnDdGtQZVtvntw1Iiod8LRkfZjptTSsmSsoe+o9Fg7eHdE7UrnSvtTTOYc2jNpnchyc7dt07cRXE4aVAEB2Alu72rxH7vYsFHhtnEwpvt46Pv19v7Ub9tD3xNErg6a6nLlNVfU5UhpxWJw4UV9wGdT5H+XzAVaTGrd02oJtkXNcx3fqiJ+d8kfaL+f5qcfQdl85NbSJ9Y6RQ7U2H22kSYePK/3ELD6od+zEuJP6WIO6tDVjK5O+uqX1zWH3DlRNXr4i3KOZdKP2OylqEYht6qulEcLeXXCy2gzvaTGfOxtiPCtxp98UoDYad5RZ0TqUl8ILZIJWJIblDkSLjkcEZuQwpaA0KR4D8YRdeGJxpxlUHny8xEZLQ/TdFU+y1V1y+zgwq/zjeLpPbZOoo2H1ldknw+fLSZuDo3Nc/9g4I54i++cBqsTulQ1A2NEaTJaA2/5FJwHCeQcD3b6ODgaxocGQsTJ7FiE3Kh6xIGuzBzFX3CZwTyXlMoKXSi8cChlA2V91X/jt6SCWmFCsmS8el9hJrnI46ctdzNZmLEzvwLV0skXZ6PISzgwA7apFqVZDx//AeeLxcYJp/C8x2hzK86iCQxwH9JeSIc42KvGSlAUFeqqi09lcvfk3cCwOkRMm5iXt2SkxO83GYVIAHHF65NjfiX97wLpv2XIvxNZ3POK8X1jNiRwSfyBfwgHJAR5Y23wvL/HcGps/hBeyzI2+dGraLlitw0ik87lDr/ZDhx7vf4t4aRAbSMXM1+fAbOx3+y0xowdSEE0B7E627qUuLGYupojjnyQTWkYFu8XEN0W4sDljw13WTTZG/FsHwOyGTG7EuBOXFcxJxiWhe1She8dkS395AwGgUUovMhvq4kX7EPaEBTNkPbLGzRjt66l6sOEnkPlo3zwGTNdqDDH/yPkRa4I+xHAod3lpNnOh5bPqBxvH+Ruc3OgtASFxPm1yvuyyYKqXYAzBI+Sr3eTZt4uDhWfB2yB3z043reqM0VdiA3tsE+LqrsvGpmr6s79EFQW6c74nYQDew74J8rqSJKMjyL7ZjNzlfSj9R4dCsQjC1EdxTacun2/qCXmxBd/5dZ0rDS0BkwN8jAr2WZ1rqlVh9qsmvfhesceTgxPP1gx63/6JsqXayTcOQSOe2+fm3zEaR+KWSJcDo7ZCPcWtYLmkQ2t6KaiECqHUB5uG+MXHq8Q8tJx2uQ4jtJsUpuyO854vlYGoBGvVl5K0F/2LYl8F9OCrV96XSUev34i/8aL5N4LvepLjxmUENBOzMnIGfVhPM18vzBcjo46nNR9itS5dyHzxOn68N24/S3fvTt9BhGF6PpDN/GD2ad0VqBJSiu/m9t+dGRuR7YQoOT8LV7JEEvMkd6OoqBT6FSPCsGAn9QWuHhdSQOWBDmM1lJNjT6+5ZVtqu8RVVqEHrne5FOLxAIUcKXKBLyUVgngp2ZbSKEc+eEf0dQcs2B2pmO6zwzLfbnDkN4+R8R3Sn/eAZAFHElo79ZxhJXaHTq9Y4DjNjZ5WXXKlxNzgLHAgHY+GU3Xt/dIKtq70cWRpFw0Vc5s3T2ViK66GIECFugLZOtLmGbaDZ1iezr6wqIArSTDxvFQ7a2EHzPTJnyGpHTerxFpoAnrSdFOeOZ8M9jXXdvKzVmSXRP4Hs1V/yKjQcHN/rEysT3yQggXyYoLTlu4xk6Pgs1oATLqX9/BbN3iNfrx7zjGVdDfiynQ63ZTjxrkLp86Ffs+y/9xhRN1vDE5qX31U6DGASfJZhGE+ZMj55zudf7+lrWWy3YLgHSaCSIceFHxPHdkim9UWHoTGzqg/Y878ey9R5EtWXYKBvy84qzQhgwzEbyjJfj1AhICSgs0F1bU0/INLLhdU47jpmCHpvdexQIITaVyUXfkSi+PP0ZeHSq4/NbWK8WRrifJL90Zt7EzHCtjITE3IAh6bZfq1eNt0w7ljxDWH/G1LRJJOJarK74MW+93xK7pucK8qQzCWiILvH6PAPMwtfF9vqvQg5QB8Z95P0rs7eKHnfUxRDouEzC+y0RvGgQ0gHZLwp7ahGgVeLbACs6eG7yoOnrvjcyEg9HtKk357OZFBEeAIshKy5x6CHW2Q2GLA0QC5rUX5rxrxhsWwg+9N4X3+OhYnsQYfVo+vUwa9S/pVXGA8191ZzjxGYrCs6Co9rXN5q8qQUvwa7W3Q==,iv:EQWRSzzDpE+o3f/GVDDI4MKFpCGvI8b8tTOlu+CCaTg=,tag:qJrHn8ymw3pX0QxMsbMMnA==,type:str]
        githubConfigUrl: https://github.com/truecharts
        controllerServiceAccount:
            name: actions-runner-controller
            namespace: actions-runner-controller
        template:
            spec:
                containers:
                    - name: runner
                      image: ghcr.io/truecharts/charts-ci:latest@sha256:7541472ba15b8488c54651ef028cbfc286d9a0c72fc066500ae2c6cef60ba84b
                      command:
                        - /home/runner/run.sh
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3N1pvRnQ2ZkVtbEQxY0Qv
            Tk9PL0xCOWVKTU56a1k4L1oyWVIwZWJBREZ3Clo1Rmh0cjBZWk0vMi9DM0xqd0RL
            NlF4WUNCMFFlcmx4ZmZKYmNXQlZKSVEKLS0tIEhkRnltalRlTDR1ckRXYlNiR3BF
            Z0tEcm40ODJKSEdIUjZVOFVraWVJUE0KofY+CkmxRN4BtFgH235KYlmDKfY6+HvQ
            AjKSeYIb70L0Vs6bUYruuL2lmGFzYpuZySLHwzK8GIThE3U4V9ltzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T21:38:36Z"
    mac: ENC[AES256_GCM,data:YH4BEGZNgxh2Xr2qDhgkxPVpD/QNEPJrNIdWvqk3oq17gPCikAtu0Q7zLeJfOntJAmSTwyfU1OopzONOSET4dMDrf3Tf+tPz6gefdF6gWD9XQHJ5zfR8VqHzMI7GA1wIPp+4xtMu/wpMzcGxNaz0rJdmLAMvFvAl3y08AY+GOsQ=,iv:WCJQuQr71xa6UOgkGMowg6VYMtFh6z3Gv2jVo/axouE=,tag:W6jMuCHeNS7J+++MYvmYcA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
