# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-small
    namespace: actions-runners
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set
            version: 0.9.3
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            strategy: rollback
            retries: 3
    dependsOn:
        - name: actions-runner-controller
          namespace: actions-runner-controller
    values:
        nameOverride: ENC[AES256_GCM,data:omslPlt19GyhbCICVU9pyOdm13Sp,iv:aYACnUYSsJRfSIpSYWxHeaf2YER+XbSDJmAz9rDMDkM=,tag:ulBLxe9NB2N55mqAVhpo2g==,type:str]
        runnerScaleSetName: ENC[AES256_GCM,data:eA9ch5CrNKe01mCV2e2g/HWSsJjw,iv:jMMoQ/V5Esw2WkBaqZPdIWhmhMJO4/V6wFDghAknnXE=,tag:1mzZVO39QmEVDKlAe9tR1A==,type:str]
        minRunners: 2
        maxRunners: 6
        containerMode:
            type: dind
        githubConfigSecret:
            github_app_id: ENC[AES256_GCM,data:mdjCBBcsjnXHNtXfMDlbuJBP4l36dHhCgQkqkJiUYnCK2Pz/KUEGbAw=,iv:2wgLQdl7jBDCh5fYdv5H+GAx3nU8/X/4q+UbvWpcMpU=,tag:TCoBMPpt2Q9CxPdIVB0zTA==,type:str]
            github_app_installation_id: ENC[AES256_GCM,data:WL+TGC/62ro=,iv:M7gdTaVAaDxwC19fpX9WDdMFqrjiEcWN/PxkzTqR50A=,tag:blcMTXyK+XuwFE+XLf3Hfg==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:z2lwgluDFdMFl+qaG8CUEhWl6yzZjhez91hzEAgrqkhZTpaEymvg5Cm84WFmUSKccfqSflulDs+SVaDoswyZJ98v9wBLEg5ymbANx0yUFP1CjTbHSQulmUeI3RrfAWa8y+r6ABI1TNEgVqwYQ7jNTzcVyztMw9X2Hai7j0SmamqpUqZ8ZC1sGbruv50HzF7hfxm/WgS0iADm8D/mNZGE/gs2N8Sa0Tmvc1U4Y/sVwFT3AgZbe8nDZtOotq89tuw4Oh7CySnS7M6hXGRhhks9pwx0SOg6dwBV+gMrlfS5EBa1GGFDmQiMM4goOzvW3wLP5SKb41qlS0MlHjNAVWE/dU/HTdDYoJSMc2d6NGDPpHwYcp5ob+hWpBhrZVdyCpj73E2IzCmmg9GdpESpo3g6pBLlIymlmgTvUxHNwnWVUuTbKaeDAC45cZQjhXC9qkbQhl6IavhfrgVBFKKSGEQFL7IuUvMRiX7QLpdiQr6txC1dg2V89w+N15KJRpcXUMPRE/q//hwsfWey8O9m2mKMNk7fjl9+nNCiPxSTKSgSAvX7ukz0kUuxG1Nn8axCVqGyN9vl7pbbQ9tRbKpT0ty+nWyR3/mfwRWRPGC6UmYxGcrB7iZ56RgXZUdvDS3kzPwvnl79/W2EztzSiA4iIBchXueOLTscdD0UD2Wn0lvDeSPuGT2LMX7xKuFjJuWY2MITsIAWbxE6d3RrSQeRr/vPsy/izEgnJeT331bEyVzcRJRK9txLnskPMPyN/eYW4lX5LFgugzf6UnMIC7Uo+YSH8jvoVQ6C4HulcJq55hV0lTeOgPx5/qK5g5IT04ncdaSWZEYxACRj34NFnzu6uUWT5E/6ofqymd9URqIfH0Eso/dOc/Oq8pgrwrMWhULBsvx14YaqsR0Vr98lIhZH8c7/PqmsrxyBVOjQZNPk1EvkFVKlTKjb+dWpVEAAN1FO98ke/zdQgtgZTZIQsPKg42yxtQN9EvPLdRSn3leGpdyz3lLWB1LNA7vSipRRyCh2nZkXc8fvTmE+kvbO0tycNoSs53AVQzolq80GA17sR58pLmXataTa7Qt2+2NmEhcIr/cWUc6nRLNHPBh+JEZE2WZ1b/7EBBMRzcx3+4mPRDa0F4AuIF760ktLzQue5oYDxUiYfh8LiCD48lVTRvOYmrTnSK8gbe/SEei3ZaPWunnVB1HxsmPDJTppT777R8GTOXj0v8ViY/ILsgjQkyjxFbFCdjZWf3WTbQw22zy67IBnGIXl0CVxz10TKhweu5ljz+Cgk+i3/3WKJ9WIX0c3pfbdfxugRO7I55AUkN1h4r49xT1ARRstA3fhgHhCg70cvApxV3/kMg0VbkcBmcpvTXihnrLjl78FRNGcwRJ0U23YKVwT7Z8N3c7V1xgkOjJCi2nBIMDBeQOiDZ1jwTc20ICi2Zi6d66ftIQlvl3sLw3xWOmV0aKtbZ6NJGkGX/upp+BOVvlWkWBJnY65cGyvNSXPsTrZbs9Ll6KyABULK0ek4dBsv6OuNpYjuA+9UH3l7407y4TjKpPe9iYKFaDin2fbWEw1Az0b7fFfOlUEK58xs8XX+mVM6bKtHpjdBKFbbE0pY+Ezqac/MDKQpuHLldUW+08YOOSGBvAbn15MEcblLxoCrLsxbgaQhRJB+FcvE5pp3aQaRDX7MdbY6XvEMe4BUhNNoU2W3Jb7m7KA3k5ibt6XHFi9ggW75E6AziSS33LV3xhuS82ujhzXfDS7dUXXIOzX9QnX1pujyDVdQmhZccZdhiKRMg+nVY08JR5jH3pS298w8Q8QWw2wdll78F2nPmtFgzOcR8pxgzTrxwHPUNbUqCin8iWbsJ8Z5/jyjBXkNDCiYerng/zH/mIwXpcws5gX8lcpXOU4jaPrj/iqViRARka2EGnv9HLY3T6Nec0Vt3QHZiFyNlh/XD4iyUu2sR460zcJm4W0h0/qso1j7iq4DCuIpcCNi5BpHCSrRZhIn7a6vbubfpkd7HaB5cyv4/X9ag8OXtHxy7Sis3uge1iR/9s0APy77YRjHyl0rEYi1gvUNmoCBOV5MzLUMN0mUZkoN1uHiywOc/F9bDThWUMqaHP2Yzv850OxMRr1Bkc1EWg4xCFCMOnQ7eohVbxDDvlSJ8RYDGPIh3mpVviwUKxYzbhm/ev5kpB9CHHwwcH0N0PJPq+Tznc0bKJJu8bdI6Bauv3bDUKJAa4fLqVvRQsKhIZm33uEx26usg==,iv:Zn8BfhPVHTTxF5o411Y1OCYqw9rEXCG+h2Ya9/hCvZE=,tag:FIGP+wRqSrTI3Qja2NRCwg==,type:str]
        githubConfigUrl: https://github.com/truecharts
        controllerServiceAccount:
            name: actions-runner-controller
            namespace: actions-runner-controller
        template:
            spec:
                containers:
                    - name: runner
                      image: ghcr.io/truecharts/charts-ci:latest@sha256:7541472ba15b8488c54651ef028cbfc286d9a0c72fc066500ae2c6cef60ba84b
                      command:
                        - /home/runner/run.sh
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWVJwRlJCZjArSnluRFcr
            aTBSc0lGR3kycjAzOWFIYUsxaFlVSFQzaGlZCnVrcjQ5MVVvVlVmRkVRWE1CaGtU
            OXUwejJvQXpsbDhKYlhGUjlZZzZkT28KLS0tIHVVWGU4VTlzN1l3UGFxY1NJSjlu
            eVN2TGIycm5jVUdzWktaNHA3VDRtTmMKHlpJbU0n8vM44OO+6F0wLLI8fQJ4HK25
            AMZP5Jwbc8ULwZz16svnzy43n3AOJaIPkjT1NLz8bkvLjXwsKIBccw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T21:25:58Z"
    mac: ENC[AES256_GCM,data:9gcg0zJ6rHiNfGVyio/cGbPSR0oZdDfiA3tiCmgdJm5cZ4rCTAlsZ6zS+c4q6gGgImYZrFfgHPO9kSMNN7HrFFkxk/2TIKP988rGShAk3RLYVdsgMzz/Nt8zM7lhUuPrO6pZUwnJ3DBmfqL3kMVeuO/FqHq8LGKvQP3DdvR/V7c=,iv:mDBiDYzdzl/NbS2R5jQ0v8elAGxeofIiJ4R7hetCSss=,tag:+vBsFwmbzDrtD5ov6A3A8Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
