---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  interval: 15m
  chart:
    spec:
      chart: docker-registry
      version: 2.2.3
      sourceRef:
        kind: HelmRepository
        name: twuni
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: docker.io/library/registry
      tag: 2.8.3

    persistence:
      enabled: true
      size: 100Gi
    
    proxy:
      enabled: true
      remoteurl: https://registry-1.docker.io
      username: ${DOCKERHUB_USER}
      password: ${DOCKERHUB_PASSWORD}
    service:
      type: LoadBalancer
      port: 5000
      annotations: 
        "metallb.universe.tf/loadBalancerIPs": ${DOCKERMIRROR_IP}

    ingress:
      enabled: true
      className: ""
      path: /
      # Used to create an Ingress record.
      hosts:
        - dockerhub.${DOMAIN_0}
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        cert-manager.io/cluster-issuer: domain-0-le-prod
        cert-manager.io/private-key-rotation-policy: Always
        traefik.ingress.kubernetes.io/router.tls: 'true'
        traefik.ingress.kubernetes.io/router.middlewares: traefik-chain-basic@kubernetescrd,traefik-local@kubernetescrd
      labels: {}
      tls:
        - hosts:
            - dockerhub.${DOMAIN_0}
          secretName: dockerhub-ingress