---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  interval: 15m
  chart:
    spec:
      chart: docker-registry
      version: 2.2.3
      sourceRef:
        kind: HelmRepository
        name: twuni
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: docker.io/library/registry
      tag: 2.8.3

    persistence:
      enabled: true
      size: 100Gi
    
    proxy:
      enabled: true
      remoteurl: https://registry-1.docker.io
      username: ${DOCKERHUB_USER}
      password: ${DOCKERHUB_PASSWORD}
    service:
      type: LoadBalancer
      port: 5000
      annotations: 
        "metallb.universe.tf/loadBalancerIPs": ${DOCKERMIRROR_IP}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik

          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: dockerhub.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix