apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actions-override
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: actions-override
subjects:
  - kind: ServiceAccount
    name: actions-runner-controller
    namespace: gha
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: actions-override