---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-runner-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-access-role
rules:
  - apiGroups: ["*"] # All API groups
    resources: ["*"] # All resources
    verbs: ["*"]      # All verbs (get, list, watch, create, delete, etc.)
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: actions-runner-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: all-access-role
subjects:
  - kind: ServiceAccount
    name: actions-runner-controller
    namespace: gha
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: actions-runner-controller
spec:
  roles: ["os:admin"]