---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 5m
  timeout: 120s
  url: ssh://git@github.com/Ornias1993/cluster.git
  ref:
    branch: main
  secretRef:
    name: deploy-key
  ignore: |
    # exclude all
    /*
    # include flux directories
    !/clusters
    !/repositories