# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-large
    namespace: actions-runners
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set
            version: 0.9.3
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            strategy: rollback
            retries: 3
    dependsOn:
        - name: actions-runner-controller
          namespace: actions-runner-controller
    values:
        nameOverride: ENC[AES256_GCM,data:qHDFFA2y31OX7s9HTrxBwuTL7aY=,iv:JknIj+MMFD8FadUzqBgu0eGj4imQcAI0Dub3EsARIGY=,tag:/OPH0sve+34YEe8DDp9Urg==,type:str]
        runnerScaleSetName: ENC[AES256_GCM,data:hjx0so+Y5+5oaPwYldlTs6wBLkk=,iv:Tx6RDLI7t6cFNPHKz9Q6tk3aN8mAJQ4bbdEhifrX5Hc=,tag:Kvb+QShO4RBxWTL6Yrit5Q==,type:str]
        minRunners: 1
        maxRunners: 3
        containerMode:
            type: dind
        githubConfigSecret:
            github_app_id: ENC[AES256_GCM,data:YqsNxKJ7rhY4DGYBydSzICdpe8mPz4wF+uTa1w9yxPWcgOgK4vOT8V4=,iv:v9cD9/qtDahgn1PewPHLTyC497Zp+G8AZKaFrnHkQOw=,tag:wtQfm4zBQfyBUeEGLgwFTQ==,type:str]
            github_app_installation_id: ENC[AES256_GCM,data:da5/Zahqd0Y=,iv:/wpTos6EN5+ZkoHJie4duEfIlgjOKO8k4eXTooVLLc8=,tag:eEzxG5BcaDbQU7JcR2pVJA==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:Ifyoin3Dg571OOGFunAMSRWk5Gg5kua2MS6K5bqqnqKUjPFXcVtNMc+skriLyORV6bPePNEBtkyvvBM1cDD325BW7wvPKrE7x3Bj5aScRTNPJog+gpcrn+FIf3x9WTirV7nr1RydZhSoOUwi4odp6NH26giOigEPCefsnqLzzYMC14SPeFAVM5fhrwXrMHzRhP2iG6eG5krrrfrWELmDUBGVIbJ/oIxrp58pu+NIadHZgUu6cgWmIWHhcHFVDX29rTfwie1PFEBPQH2Agd4F0oa2GXOIvTFk6tyEsaKdWr5e83ivEyiDKDQR7BAqtfQGRqGsXPPdEmDzcWoN3reW9Xbmjra8l7VlFvGxGgZ7paMuZppWq6sOu0ZgvpUe8HCL9rIvxgpM+CCmqR68SZlS1azKxG5Y7STBg48PXzexBcJENyrl/79AiSetXmygIj+T0n8dMz87qI8hegB4Zntr1dZ4MigrGJRF8j8ChhwxlQYHN1KzUJSZbhQosYEWicNMdaUPlRYbRn+0zhLuBhGkL87poF+1gIGBT2SPYawDubkGvPIPUwZ+9f7Cg0mMsRxNOO++jN68fl3yp7EtszhGzDqLMXwYE5JmF09rROd3hAYuOZIX/KQA0vnRWgEJ0VYtOfvq7CrHhxFUZwAm6Xg8BZFEY/aVTspjmBMcG9ABE7H7IlP+efV+t/h+6sPn9SJYcpvuK45rlnEDaypQzGeZlCOWdy2FJgbtmB0vOUqjUcX9wLgiKBmsRhFJq8wHBKs/XEYsS8ETXr0gkQLbV7+iiD+HR+SUy43J6JrQDYjGJzYUDlRWM3XqnjrSljuObS/Sayxc2HzZhj9zBvqGlFdxnwmIuS18Iwh/vLMLJBYviaI798M/QDVMbSmOrV6skocjxwpLwH+AZtyLVS4taLqajeL798DGaGync5RlaSnVMzkbnjys9dmVNk2tzCfGtZYPa6MUZW2f+9nzkYdTf5a9xtkIFE37KLASue5ztz5CvpsEpzrxHfio6P3ZdqIXPSkjHbR5M8JfJsMDOwGMr/VWx+uOPOPZ5QDKvmByeP5lLnWX+IT9LLEsTOiiTJAvUYvkIv723nEJssAKUE+uinC2JanMa536DjiR/Wp3cQlfyBBT24pN+p1RIzJmJdEAboU01RZG8uCi/HX5kYRF5v22i9DaCVJicUii9mrqNBo8vEYmGL5quifJTL3aaihF4q7NKSXecvp0/lRkMFuBo9sJUebs+sRi6wgWoL3RC5ZNMPBdefaQGdOdlzRJWZQFlu0VFVNdopHuftmj16/H+MG2S0fUEwSn2prszMeiOAw//Zdik8Oa5RhM74bUdDCOhuzlRcOv5I2JFb9nllBA85VkrjQrxwWxDoz4cqpkocgoj6nPditijnLLi53dxVbJ4xFqcAJEU1+6KEK2cWfhfcr4kt5W1j6TM6hF9cuMO4RW5VtbNNjyf8MCUTrJC4qSGsMNaNoOtMcXdw4Be8Vhgqg87Tg83OHxDftcbxNaOiW/7f3wi0FqEcN9U6WuchUGUT94hRaxGjKbK+TNYNcsHax1YrWuRS3o4VmSntgpc6gaaSAgxf8sPKp1F4w/JuF02iIV1Z1zdXp+JcMFNB2s0GMR+UsXrav21C2tVeeFYLj8JbALbXnJ8xry4UCTp9POKWMZmppEE7h7yfkn0c+L+SpjU+cuipro1ZWGtnMUCWMfE7/UB8nC28+eAhDDMuFyysc4RJBz+4xPYzxswxblo6YF/KtwFMhxe1T11+DKTA8gRuZSXqnx0RlrfHTajZHXR5VhHWZlHWHM7LYQRKBa7YWquNz2p0qO0+yjOV92TDBZ0Kd16Um6gxTUP9zoRZNcUKskimWzRmALTXaJdFOaCps+5L2ZZaDwR9q+GUQ1mCMR7QEgzdVBq0Si3ZhBOlt+jZmBQvOHYydPeQxSBLoKmRz2VG3lemLq5gIsJxd3kam6Rf9iEglK1Ihwvzi1rjxPoWRIqyuxE8xELf6cQKKH6ioupwRKjq0A8iMkF79AsZmm1rx3jwDkW38KH4V5Uo3ViDpNKsC/ahanUH0Bn/GM8mH76iX8nhy1TEjOREd1NFVgcygWFpzl7j6cIyJm6gmp5GrVyWmVKonR0Z0ivwGjMomB5TuK8n1cscT5VLTfvnJewWxgR89tbuCVrWqADl6ezma7GKXioaFL4XazOoSL+nDGq/xPoCCsGT9E5YsEmGJfYGfnPOGBGQs+O8phxA==,iv:w/GF57DZ76s/CQyJYwdt6turYXHCXlC2Wq4/K58KCZY=,tag:gKpE02GKDNw1xY3DeXcJxA==,type:str]
        githubConfigUrl: https://github.com/truecharts
        controllerServiceAccount:
            name: actions-runner-controller
            namespace: actions-runner-controller
        template:
            spec:
                containers:
                    - name: runner
                      image: ghcr.io/truecharts/charts-ci:latest@sha256:7541472ba15b8488c54651ef028cbfc286d9a0c72fc066500ae2c6cef60ba84b
                      command:
                        - /home/runner/run.sh
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bElvbGdLRHFYVmtpQjUx
            aFJKTnE4c2NOZXFEamlnRytjRU1MOSs0MGdBClc0VHMxR0NxSHQ2QXpxamx0eUdh
            QlBPNEVNWGduZHROODFiN1BKQWtFV0UKLS0tIEFTSzJ3SzBFMS9KR1dWY1RMbFhW
            eW5DWG5mL2VJblB2K0RPYVJlWXlaejgKGRfLIc8IdkDG0ZqxVQRN8Nryijc9Va/e
            wiGTpIh7llMaiVY+RcacXtoEM6cHwUb/ifix0A8+BhvgfFzWIueTaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T21:25:57Z"
    mac: ENC[AES256_GCM,data:O6V+nLs8apn7T1klO2HaBdW08u9A661NGntCbC0TuL36j6e1pQ/uydkjQqkiX8k8FEVaDciYfVTxk2WwWWO9YOzn+VLY/nNMmGWuaV4cPwkReijLcEcrG8VLW/+XiilLCNiCK+g9DeL4GBgJhKiLEa1Xr1oMvk8kjjcqs3pPmVk=,iv:4ArDg8sWv7tB+R9J6RZXj1G09ra69M4TWRODLE5vTTA=,tag:6iYBnZuWnEcw32Hz35gldA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
