# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-large
    namespace: actions-runners
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set
            version: 0.9.3
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            strategy: rollback
            retries: 3
    dependsOn:
        - name: actions-runner-controller
          namespace: actions-runner-controller
    values:
        runnerGroup: large
        nameOverride: ENC[AES256_GCM,data:BiNYq9bfobxmQ+fxLzi7La0mm2g=,iv:zu3mT1H/npI1HHDrHhK7NtcCsHrMfrAGM2GT4NdJwBk=,tag:3KGikRKIrkERneL9O/PIOg==,type:str]
        runnerScaleSetName: ENC[AES256_GCM,data:N/rRU6XeAVHvMOWx8K3ge+cOtn0=,iv:Q3hZtBggFQ1k/R6lNXNeZqjuIRJqKV1f3PiWsAxLHb4=,tag:mlAc4E/gDyablC0yZc0+sw==,type:str]
        minRunners: 1
        maxRunners: 3
        containerMode:
            type: dind
        githubConfigSecret:
            github_app_id: ENC[AES256_GCM,data:yHWaqXzgIIZi8isogLUwnCyu9uFrzmh5Xv4uS7JDOSewVIlHdrvCwP4=,iv:MuDWnJ+ip0xSSfuhyD+yb8vy+gvA0rLUR+41rIsqwWc=,tag:RdNJHiwbWL7HwfYx5YdGbA==,type:str]
            github_app_installation_id: ENC[AES256_GCM,data:ITQcFG3mbdI=,iv:Ujts8WmdzrDWZI0UnS/kZULowL0gSQ42+JaAtj0PVOM=,tag:MTcraWPadixZKiU1Mj6SPg==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:gLCjpW0Ubnidj1x7mcw/40o42giOssaP1esgd16sr/GiQw0tX25QLFWjl1TUwJ9ZVb1EVjaBnZiFT6+PwqHmPOrsUvnRMlKFbsmtlLQNX2vpgNko3uJh5aifPur74p3ysqSHuXG+65wE06OplAbxKi6o4W6r6PgKPVQofLQ+bLdwe60C9WhPKujxexh0gN0W14/F9NyyYkaftNdxb0HuI9V2pRzUz1K7jUs3weDrZqO5sGj3BmCZnKMSRw0/2rEec9cbTFonOF95KcDGMiW4kCBjYmj9qZAlSzKhdnOIeMpibgHrLaYMTuJDUyB3jwzPHxL9lZe+XCE1/jqiIGESFfwZWHDb0/b9CvLJH0GrJIO7FJy63eVhABSSdvQRe6/QMskiW1Mj6kB4NIYnf/GxFkIbwZ6OmsQp4up9UwY3RHYGREXatWeuhCQD7huIU4pmATAWPQFzRSbs+xE+g46Zs3f5CqzDYqslGco00TfBYEF1uMyyHvu/xX3l735WmWoEheWAElfOjUidePZ0II/ugso0lA7bCx+vdyeG5xhzqJAD6/Nc36yGYwKZNzF2kg50etCv3Un0K0XSM4AvmSlFgkMN9C6IaqIcSLLQnLcDmF4wniF/230qKBKe0rrdbMNk32fULJZPZVax+Wpx/JCjy2hg5qABNWJt8NzfKw39yXo/G+8QjsFrC0XxEsgGl/9YJcyCkPnhcgPCovYPhMG1JfgFJpJZR3Q216tc6c0/3laQFYk0vyEwNn/AwIivbTFskOGEEHvf00rLCFI2ZEG8gwORtl9cs0mMKK9wYSh26vo9MWMF6BO7B8GdckOrMmqnYw8/a3cItYUg08Jh/Xk1QDtGLoxKj4Xaw0wTrWk8Wizi/y5cB4Kvf//oya7a2odAIddApSkh2afbF9DlZMiEBBQLyISf7/lGiPHYE88CTI3I8Nc+8LuTaTpT09SrFOAU1bljhtH3dH0FQh+Sy4gkmD2nflFXY0uBfZv9rV1ThHG1MPqVjtplH7IaNkEeWzZXnonSAf+243pbHSK3pl/tkSUfWerkFEo3P+sA+S7ZAiJYXA993DNvM+3wqVlTZXw4WZFRADdjhuByFZnqKfSSEmq8JH0h6LBdguA9jZ39M25neQIo4JU8fUbgXTm0ob6PNnlBYWhBQyFva0Uj1pvLABtfONjd6Wg1ekgYSXcAgRHGg7+q6soon8mqteEpbyo5dbQQ2VVKAPwMZroeCh6KGc0lvn7RUYvavTzwzA+UdYCg94A7g50+7z/OvicvWvCOvP2fuTc9D4TTr1Qxdpup3RU+ui+cfF3dltyhsXI2fbHV3uFVGn6YpHyrVbniZQvjsg27v7IxJvTQn2hbbVh+jqdDuxBzM7NpQhkgIGAce5ZRuJ1p6BoRJTvs68fjUL8d6Ml0dq3xhz+9l9sxGj8H3ixAqbhGV+wGfkQqip/Gqmbug1jsYB+NWCzYcJ138d3I2qKxaWp4V72R2J/X7obtVX3Gt5B+7NpQK7MNLFF24tMy1d7oEa3HPwmmBzYJZ4+qu3/3qdLNCpmHG6etWavRxXt1HpHtvuqp2VeeASe5sQCMv4Wy9XZ03og1uiT8QiP7Xa/LER7PO+ADEN5a2HAYjaASOjDD+MFcd7Qz3pwAd7ynbc4xrG0TLQFJNR4UciHdj3icPanqnT5SOJvFc3WLlGoPYTnOAIfvS/wINSiBqSoxgvh0GBVvy4usPogQim00n95NbTwiIfZ9Aw6+dzb9Yajs1Etm1eUeg+ERR/JDCPUvGQRDBi92i9V775SR5hyBUx2UUbqtLbjfFEd0k216L4gffOSD5Xm0jIO/+a8mEwnQI6LZI5CWf3nfrN7xnIiiPk/nDYBx74FGBIK48P5paTtdfbJ6V0wqDg/MLelgQMvJ2o5GC3rTrzakMmWxw9CcuoQK6cnz7h/LX6KnjKwxF62tIGy0TKF5Ix0A7OiBr9RlTL7fpbPGtbuPKy+qrFwtUJzCH5nxnvvkXK5eF6elvSrjDaT2XWlE472/xJHBwzVB2ePzXK1nIaf1fawMEzb174UPOiINJpvMmM22fFqE2C8JB5LlUKqHGbo1pBzZLFDOsUj+93ALYR4ruAd0CWGp03seZBaHx+GGmNpf2+QkD4xnvCCDSVHQSNPttTKaQsJhO3/YVztO3CyXXk4qT4XuT8sHz3rwfMt1CG//YTiyg96HH6x89khzbGWLNJXnCKaQxo5jsC22svRhyQ==,iv:dyVoDn2+RiZsycj/liOEZ/ivIpobSMbTZHBKDWivsi0=,tag:z09bfjjmXixAURF2DuY8dQ==,type:str]
        githubConfigUrl: https://github.com/truecharts
        controllerServiceAccount:
            name: actions-runner-controller
            namespace: actions-runner-controller
        template:
            spec:
                containers:
                    - name: runner
                      image: ghcr.io/truecharts/charts-ci:latest@sha256:7541472ba15b8488c54651ef028cbfc286d9a0c72fc066500ae2c6cef60ba84b
                      command:
                        - /home/runner/run.sh
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIT3lhVExMSjVVYmxPYmVn
            aklhczlLQ2tpMmtvc3RjaHpjSEpwU0JLTlVvCm83MWJ5Skl5WDA2TEo0SlhnZTVJ
            eDFPeHZWTWcwTnorMHkyRzZWTjhwbjgKLS0tIHBrbFBZOXMxOVRuc3NFMEFmWVJt
            RjlnWmFldE43Qno5eEZNVTUxOUwxR00KiDD2Isn3nyYboJgktkaGlu164nCY9egR
            3BP8saToe6QsrBmdw592ynHFsBxzBliOZ0QJM2UjhdfJzvv3rl+0KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T21:38:36Z"
    mac: ENC[AES256_GCM,data:o3nu3UmN4OH63s/9K+d4gTPCfjsaNWDNWYyhloVy1dBx6NTN2po+LkcugvTc+pvd8Vz3xxUHXP8Yj0vKJqR82Jh8ju/nK8VQ88WfGOc/0p6POYCQGUyXg6sAUvshhs6X9skukzKEELzlBr50cUAoxufT4XzoqRx4lS5nS7dYCO8=,iv:fLXR8ElvrS3jhITcI+3apMuQaL7lxLJ6NJbnmp8mEJ8=,tag:O83oxbCVYqOOGHVAbRexQA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
