---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller-plans
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/core/system-upgrade-controller-plans/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: system-upgrade
  dependsOn:
  - name: system-upgrade-controller
  wait: false
  retryInterval: 1m
  timeout: 5m
