apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-controller
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/core/actions-runner-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

