---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: recyclarr
      version: 10.0.8
      sourceRef:
        kind: HelmRepository
        name: truechartsoci
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-recyclarr"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"

    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:

              capacity: "100Gi"

              accessModes:
                - ReadWriteOnce
              enabled: true
            src:
              enabled: true

    addons:
      # -- The common library supports adding a code-server add-on to access files. It can be configured under this key.
      # @default -- See values.yaml
      codeserver:
        # -- Enable running a code-server container in the pod
        enabled: true

        ingress:
          # -- Enable an ingress for the code-server add-on.
          enabled: true
          integrations:
            traefik:
              enabled: true
              middlewares:
                - name: auth
                  namespace: traefik
                - name: local
                  namespace: traefik
                - name: bouncer
                  namespace: traefik
            certManager:
              enabled: true
              certificateIssuer: ks-le-prod
          hosts:
            - host: recyclarr.${BASE_DOMAIN}
              paths:
                - path: /
                  # Ignored if not kubeVersion >= 1.14-0
                  pathType: Prefix
          tls: []
