apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: rook-ceph
    namespace: rook-ceph
spec:
    interval: 5m
    releaseName: rook-ceph
    chart:
        spec:
            # renovate: registryUrl=https://charts.rook.io/release
            chart: rook-ceph
            version: v1.15.3
            sourceRef:
                kind: HelmRepository
                name: rook-ceph
                namespace: flux-system
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
        enableDiscoveryDaemon: true
        crds:
          enabled: true
        csi:
          csiAddons:
            enabled: false
        monitoring:
            enabled: true
        resources:
            requests:
                cpu: 100m
                memory: 128Mi
            limits:
                cpu: 1000m
                memory: 256Mi
