# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-small
    namespace: actions-runners
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set
            version: 0.9.3
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            strategy: rollback
            retries: 3
    dependsOn:
        - name: actions-runner-controller
          namespace: actions-runner-controller
    values:
        runnerGroup: small
        nameOverride: ENC[AES256_GCM,data:Dmu81NCpXqPYwuGOhtnxD35qs5M=,iv:kRl+/dgIE+nPtYitC3BRuFRR7v/8JTojDgUFJiRImeE=,tag:9AazSJsuL6bP8oP159ezMw==,type:str]
        runnerScaleSetName: ENC[AES256_GCM,data:Ozsr/22W4yPHG0fmCKTf7hMcIys=,iv:Atz4oOin6q5mrxCnN9D2qwVtmTLyxGZtHakZAWiZCNo=,tag:C7kZrZFvON6SeNEnBFMYDg==,type:str]
        minRunners: 3
        maxRunners: 12
        containerMode:
            type: dind
        githubConfigSecret:
            github_app_id: ENC[AES256_GCM,data:Yyespjqqy2G6eCJR/dDXOWbNJDTPTlMs7UAIziM4ex8o9DFJidcVXy8=,iv:FCjV/j+TASthz+Ij2bNTIOyU9wtHv5/J6MqB4UOR0kk=,tag:434rUBPkJESJMiAiiQrYGQ==,type:str]
            github_app_installation_id: ENC[AES256_GCM,data:avbu4djOfuc=,iv:BSjTKIFN5dwri6jHMBOqgmWb7/Scfv63AOnF4ypTQBw=,tag:WtuyUVTK01splTnwwS889Q==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:7vAjc91D5zggTByLY6oTOclLmzHhndVJtlfXqEYRDBrTm6iMt94C7k8z23obHboM1rnni2poJN8hutbEbU72pcWWMPzK2R+MugDRhvy3uRkpZYjpGYdHzwJAAt/MmptnOP7Jo2hJvrsWwOH1OTq8k23fESQlJbO++fjHzlznEdXQt2/AT1TcIKTtb29So3pkGUKDhdONq8NyKYBNCc5ZZ6KURvCCT9RihyO2N2/adtPPL5ND1rZACjofYupNeKU/Y9Lw3lGRiWfQjWr7d6CQkZHMRE4ODazyGpcIiQ0JKCxQ/szn00SGrzRTSiY8HwyJJf3mpDHayaVWXvKknxIqR3sLbZOklMExO6pJyfcgOfWr0XKAOSGigPd6xW+yilvSH412bbkAwEdqC3V1qsd1O2ALw8Wz8aNtKsgnpmi82l9a12b32UCo+VorWG0vsRxWE7+Uc0dO9Ag1OMakDvKymMWfas3fLg9tXO85UER25c8QUA6Cne2wfsCHYKbUrwhaTlJKvdHbdzY+TCUzBoXcbEELl4p0UshfXgpRlZZp0PpjGBf31qKNXBmgObx5m6sqxM60rQ5KeLmPQcC7PxfmeFNnsheKtIyyyDoan7EmWfPrLDrB0TUXpbHwUhZDvuAsPwncFZ93XI1tLYrizocGHfQw/lqp9icPhtd+ceSeX9kUE6/wcZE7EQ+8K1tea9y/lNva7x2tJQZvMGEETeIX9Lv4t4WIGBL4k0cdL9SnEvSsJ+9CHK59GinuHx8pk4pFZ2Efh7MhXIPNlPPrGHfZHTk01dGLILwrhLeZAcRVcgwOOg5X/2fRsYyK3MqaznIraEyjaiO6Ins5JpY1fwSY2zOBnCydjXLPhCH/jhnJbukBYzVJwnBYVVyXCNNWB42lgTvaFD1RkgpnZibYrauAtV6dOlwmHFG8WyDKuQgsvQrMwbZgrwOIzVTSi71d2LzuRJlx5oqT+jIsabEwW54ETObrv3GsRFhH3INezeAfYxlA4PzaYF4uRE64oPolBtFXnaCFbaQ8fSa9wU5OmB+Dngz/TGSxTJ9aWW1zTKAJwOb7SHoCP9Q3M8OJ5ZrMoU0ecd1uYEZ9alreKg4/xD/mGEVRAT2+7t4LZUKw0ul+WYHpAlZ6P1HJaFpku1p3XK62eWIlUE3bucckNdxgbFkkYPohrjkgXTAdCOfdZnqIiYobUn5AgmnO9U0QPCCy8ShJ8ukrs4OedOznAU2CXIGARFYOYP0rZaBEiXiV5LmsSqlUi6L3psTnS1z3/qYAjj+8xvj+iUm6a5Pgk1UzQvDuYDAXnQF174yuID6HA05H8p1Ax60yCLppJuz0/tqcJ0P+MmxvayXjbZwBUI1aG7SObZUsoMdRAMXfOc5GZqJ/u4FTWHejcp4op6c/2Xd6FbDExF26Uve3pryqV1GiLB5Vm3sT1Wt2TOMIf4IywHQM7iaP0vxdrhK5opX3dDTnS+R91NZXXOCUmv3473BBZR/7rGSil190Fni7nZ9MQhAOPvvD76yCs3QEp3ZKJhyPT9F6dTAmvGZZR4/oYjQ2nq+rDm4ppLf5ruXenNtxNof7r20M8PCBnBCrrYXyQxCjqoFk1KOsJwo6mvP1pPPn6hb/B1Z70EMDPppb4hx0yzaNlUlr6GUnrH7mrAHHHkPwB7iA5zk1t93VLdhEgrpzRy/Z2MqM6K2aFbSFPj6u2R9emrwfIkKnCeu5dpc8qBzm+JZCg6gCtmBVPBKE5Juf4RSY3gDmQkDRj7aBAF12jbpAcyxjuXOTtRQjEAw+teDFeXP5zI1QsPmucHz8BQ6jKC/Dsm5QuOLkQ7t+LU23/0oTM5DYRJPkKOUFnYEAqdI/wKHjTzvTJaZ0x2WJbNYmWCGh3f5QB9A+bGLUJBh/o0OsasUo1u44r6SBMT0wbYhZryGWXpd4uQgHtsejpdKVUi+v7gyujWcrHWXv94OXoulRjsdegTYyQgZrdwtG6675TuRwd6lUtMNdbmIuonTVtuGOErwrTTkT0W38gvpLmtNWoNR3uhUTkAKAtZoA6Z0Lvkn0KlhfTwIBPG0NwVbU7vMs439cPaOX0qOG5/+hlYw0rAAuVP3R01i4fSfMM+/f7Xvg1v9Zaj1zYZ/4P8W8/xe5wTfjQ/bHL1sXGd1+ThqPO5tA1hGiK2F/Crxu37wdrbmIESYWarPXtBwJzXlaIPUDECMLORHNZvZ24Q6gdtVXM4XuUGrOplO14Y9KFQ==,iv:p1QNDYgF6v5Et0+Wkv1YlceXjbeaDo7Yoh0ONTjRKtk=,tag:2RhLKlv/ie1bc8PSIJx26g==,type:str]
        githubConfigUrl: https://github.com/truecharts
        controllerServiceAccount:
            name: actions-runner-controller
            namespace: actions-runner-controller
        template:
            spec:
                containers:
                    - name: runner
                      image: ghcr.io/truecharts/charts-ci:latest@sha256:7541472ba15b8488c54651ef028cbfc286d9a0c72fc066500ae2c6cef60ba84b
                      command:
                        - /home/runner/run.sh
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcDNvV05XK2t2eXRxRWZV
            dHZIM1J6R2oyWkhaYzZYMW1lc2V5NUowdWs0CndGRXhmVmEyVWtLR1ZBL2xHbGFu
            VFEyemRkYUh1MkV6Vi95OUw5TGY1bnMKLS0tIGdqc0g0QmJHbEtBdE1zT3Y4elZn
            dEJubTJZN0R1Kzl6cmtyWmw3a3M5SE0Kq1NSOEFAcP15tCfGGYgkitQUHkHec69x
            b5cEzcNIWnqCT7TAQtoJNXZbroHkm462SpkLRFExnySy8khBw9jFbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T21:34:48Z"
    mac: ENC[AES256_GCM,data:qhlit4pqRj9Un2+92dw7QyMyZpVgFmNcBskjfoSntA8nAwkr679Xz20wCKpuD4HG1dvzAS7WEhhBgIHoWibW4q/I4ey2u4mCX0e92njiQ/URoz5YqMhgOiQdcamlTHUifMmj2ViDzUMsYG17eJ7w9vt972hH56bVjhLfGvoti/0=,iv:LlSOkBrp/Saw6m83NmH72hnp4QCbamNtj+kpcuNVwis=,tag:S7z9CxCrbfHK3KoBNczP/Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
