# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-small
    namespace: actions-runners
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set
            version: 0.9.3
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            strategy: rollback
            retries: 3
    dependsOn:
        - name: actions-runner-controller
          namespace: actions-runner-controller
    values:
        nameOverride: ENC[AES256_GCM,data:d19zPx/Ku/e8I1iuMIoDoa/0nzM=,iv:whjqxMVKGTJwcJGBhWhrGCWw+BWmIZjFPOS/usuvvKA=,tag:pTqfinkiN/HvQ4foT2JVmg==,type:str]
        runnerScaleSetName: ENC[AES256_GCM,data:51yh0jObG1KzJPTRmGMUA+0gepA=,iv:d3SLGdZ3cGO0T5+Eko6ZOQ1jtQYlhiB+rD3RPHnLc58=,tag:WQbXEfVl4LQgodJDo5isIA==,type:str]
        minRunners: 3
        maxRunners: 12
        containerMode:
            type: dind
        githubConfigSecret:
            github_app_id: ENC[AES256_GCM,data:W0/hXJOK/jCQbmnkvLbwFqxJKcHJ44gwzfnvVx4wM2f3moMPQd6M58c=,iv:s4zh4GAGe6wx4vtizvOD0Qb3ate/TPqdq0DlfkcXmv0=,tag:GB5VJdZDWT/tgLUlqqeTYw==,type:str]
            github_app_installation_id: ENC[AES256_GCM,data:1DLyiPpRokA=,iv:A7JsOs2IymLze94dqIPQbJYGQSfga2r40pfI7PYoRXM=,tag:qBEuCYFv3yTttuApMC2KTg==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:MKccQu1FuqtVyVtdcfoUUKM9EIKvg/kRd708hpiD4MmfDwORZs+psPOWPAigtw3xLPP+pGsiUMNSFqrcT/HdHkk9VpTyV380JBC/9Nz32QQEWZOyjJaCqn90ZDFgTU7n5OxqrZSZouN3tN0k8rqA7VfjRKHnMSrSCUqS3A63/vQJ1OntPBUrQCLrpBc7moHtqsvjLaGQ4pUia55YjDNKnNjJ9zZH+rq4I8L9ilUgTBcppI6pehP4dNvlVVZoA9eSD0Q1iQwUd1aY9EXp6WrvwCWQeL66b+oeYBsznKmgqwO1OLJ6NEdYLhg5HCPTqtZXgES4NLSMwijRK/WEOAz+MCqTSwBC9ByWmF/jwNecuEzqnysnhP7+CschnMx3dnWD097C2qYvY4GpHaJbmis1zlxBiMeQmZRtMtsKLYN4Y90rabrVDeUTzhBdJDaJd5BRrQmbyjzSjW3JOHowUCod0wJ2Jo6KNUvlqsLYc5KWxRrdR0OnpiRfuw3yBi8FsCnYh/AQO38o0sNiHZa/0BW4kED82SQCDbzUqZYJWmiwch2bZEVEB+fZbUlGZCAW4ID/sOLMFEBAcrbp/OkKlDmT6EFOMyyILnIpesKNOS9LKReldnf0oIDUvo066dw/aGx3my3/PV4k7hqBADPRqV4NHZlGHJ/5G72jnUe1A+ptrejx/q6ljbJv3foJT5kBbR2F/2ngcSbVxtzFyJQmRFLE0E59u0fXtn0/A8sr5qCr3Cv9Hy/8hKXhycV/qGxjiViBOXtVIbEpx4J16mfCuXRLJTbqJXXaTjJLauoBdp85CIkrFqpVIW0Rqa4jG8LqVA47uqwB3d4K5MMuWYitZCYtu7oql++4f/39d4QfcLwzGyN/AVGMkTaQXdsVe6AP1bzHEIcXK+cQWRCfKyOtYLh6XqCiHFNE+LWuHMZoAr2/CXpsY0Aa6w4r9xXgaIDeB9ZQ9I1ZOrVoTeZimxZKx0z4pATcSo1iOmMKncPswwUOkB9LI5RBEua8TuZaZUQPW13Z0XwQ76DItoO94lb0HqXebNw3yuUPfTmxEVq8v3njDgjseMUJ0qmasjJTHZ00EAyRx/+67bUdxpsS6bq6VbBJ0GEGkEPumyLiopxVqlwA9C9YcvlUk/P/dQktOma6aGJZEdkLF2zdpz8cPWfrEwDRKXcW9nBDAxb3LCW20fDflTKjsgeIj10ZPqUEEB/4pXbW1/RXBE0Ci+d9uyFbXBu66L9/kGYTGTLRtseenB75tHJm9X6V8aXIPqv1ca9uG3EYZGdUnfFeIBufnwbZ/93VOnqiampCmd0Wf2NE9ov7WEWbPQvlkPuyiIrgAS1iJIMip1QInK2Ge53QIMVbRRroMQL30ymyukW3idfWndO5bnYSEShZEprJ7LH1IRnXd3xfMg0OdX2aLRHS9tsMBcmAUJ1GkRrQGqOXo3TRSOsdWxJq+v+mDwjKvE0+3LJ4wk4sOwvTqUN/yhwP5wR6LEQChMyi6cR0LIjrQWzd3GYho2HZ4MoKiRJrVgUmErwRu48XMkC8MFRA9QYycdJ0Rh9pyqHCfNYkh52L4+Nlt9lkI6Z2gIOpfPAi0kNZ/lXuAfYoGhyPZEMBVAXJJecAaN0LcpCnuZUTz/vrcAccixZ17uyohDzFSEL1FLt4oVOOiGi4/Twdl0k/Rr4yyWshBYh8sF8sOEo7a3Mra0IRbgt2ARnTFlF889ek+t5exs6i3EJsClQ4sH5GAKpXRUKnbKI1pztO17IAwWzU3DUg4ljdAenSjAC4VAbJWu8LxGpTHI3nVb6iTXZxCtfHazbRDxMb3fqgMYIU5p+3Dv30jE/2MB1pgxfnvI/ObP8QWtgFDRXLzU7JtnBBSlJAR0jOBTrk4VcQ+XMDzvaP2suoNsCdC0Qo+tL9ZtdRheSNjyBwX5bkY1T/hX5XvK8L1Eo8ECCm/oByu8X16IGuyQfwqe1klRF0WEmQzdYpSz9tpxOp9tsfZc1DhPhCmvXHNvPabhT91+59jA1hzA5XzHzu0wQO4QTxp4TK3XihIepmiM7OZfkmYH0Sf4Sq2LfE9nClnheUor0bABCID1PUzXddxQqxe5WWW45yKDwYuAEjS5K4LNW7pEMxVEWzXabvG9CJEFcBgEBd0u1pboW8LH0LZmQrkFvLZFAPOsscQRFRtWL1LNlO7CHoPpQZe/N0PIz+SkPiXNqBqEjtKmeepDh0FOsc+8lfsLvJTTs9nP7avA==,iv:AzvpLQea8pj/V9iZI3cucCAzgZmxD6MHS+XRmVEvjC4=,tag:FSsVIPuixJcKcGOVP+a/kg==,type:str]
        githubConfigUrl: https://github.com/truecharts
        controllerServiceAccount:
            name: actions-runner-controller
            namespace: actions-runner-controller
        template:
            spec:
                containers:
                    - name: runner
                      image: ghcr.io/truecharts/charts-ci:latest@sha256:7541472ba15b8488c54651ef028cbfc286d9a0c72fc066500ae2c6cef60ba84b
                      command:
                        - /home/runner/run.sh
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQlpjaFdndHVWY1dIQy9j
            ekdnN2NqWDVnTk5tZDhIWm5HQVJUeDBONHo0CklURXd4VU40dThla0duNlQ1UHZI
            akdaMkNvdkpIeDhxcVk2UUtIeHRnanMKLS0tIDY5eGhBT2ttNWVHc3JiMWdyMC9w
            K3RDNDJtQkVvdG1PbHAyL1p1Uk5LL1UKOF5GH2XT24FuPJJ1CP7J8Q+8r3mLK8SF
            ZQwG1PuLrrhtMK5yH5muAD/WH7itUD3wtQvD2bfN41OweltFyP3ZOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T21:25:58Z"
    mac: ENC[AES256_GCM,data:UoIy3t7tE5oPyNSruxXeByawekRyN0+UqjgpIgoI1Y//bYCIYnOhHyaVTdozi8ZLE3ewPNZ7ys1SSm1YgGb/AK8i/mGr+8iEKjoaUXZh1GUsbSisGbUsFI+QGbstva7BZ2WAdnaMX5SIuL57oBxRPC6D09d8aH6l8+XatpPf71o=,iv:Sw7D5TfPzKejQI1vAvgorHNpDadZEl7zkOY7698N/U8=,tag:Rd3hEEMqKwi6z8KpJ9zW0g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
