# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-small
    namespace: actions-runners
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set
            version: 0.9.3
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            strategy: rollback
            retries: 3
    dependsOn:
        - name: actions-runner-controller
          namespace: actions-runner-controller
    values:
        nameOverride: ENC[AES256_GCM,data:EGRG2RdtIK5aBXr5T2ozCljqnA4=,iv:pBaPMQRL94TdGTpoPcySfQGb2zKx8xq9iUe+spAGnOM=,tag:zbY2GRdOJLgSxhXZi+hiOA==,type:str]
        runnerScaleSetName: ENC[AES256_GCM,data:aX8eT4Y5Ne0U/J0bX0TEjBgWwaw=,iv:tNzIev9WtLh9VhorrkwExSi02kUgOghYG4DzFCFjcXU=,tag:aODG703H9afmgyCiY0n+Mw==,type:str]
        minRunners: 3
        maxRunners: 12
        containerMode:
            type: dind
        githubConfigSecret:
            github_app_id: ENC[AES256_GCM,data:UagcuU5PBWxnW9annfPq0HDJNc2Syy/h98NiL40UdxWNZoY6sdBn528=,iv:QhNWTzYP1TAYmeDYtidBl2/OfS7XKmDNa7MqYdU8MvM=,tag:2+JT1AaSDM1k4d5oOFG6nA==,type:str]
            github_app_installation_id: ENC[AES256_GCM,data:uh0hwhapZas=,iv:PXiC7BwnQRmmU9L+bKdy2fLa4g3yJ11F6DDWGFdeQSc=,tag:wiAIneAgjXt13oefFRWPGA==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:PGjkvg38xE3ZzMnjotVjch3gapchg1eRkqxb1aWSkXRt/a8xCppGkh1T8rz+m7WL/lSd+DXvFIeOp9W1ava6w2kRJmUUGg7OZn4LajsHsO/G1kHs/XCb3Zki9nVEdg5a1G7r+I27OToeK2YEM7GUMSsxbxcE0EQt1kH9phqdzvYQf0xvDiWy7vXBor2LIbm6Ess2yopO1iVj15Nu640mcY3dg2L27eab6A9Gb+CUaQhSkvbP8q5J6VweQddKSh4JJscnkI0C0lg2xdwjiJYOVMDMOp3cG1b+INjFB5PBRWBfXU2X/mdIDRqtoWkausmlQkShSWtJG54ktBWuJ4V+GKW4bs7G6xGhDKsVzGRs4RQ8Aiv70dMnHVveR3avELuiCq0KSUwnfhFbNHkijwmC0hEvrjIPaPYblc9EhY+Ek7Ej2QV70XYikgSVztc9B0GNnVTSbIkxE63CLsIbEQ/pjFkB1Kt87FH+IBTUP293nSTFtPhVUK7SVqDlmhZRu2ElirwoYluM/eBQmRQgEdcZprSp4Ghor85vgWNhuTe4wuOvubaYA3rdYXDwYh7trJ/K4lj3cANodUow+afe7ilNme5swgYxOUMCl/XQ4NLbdlY/mAgCldbObXgvR35nHS1O36puKG5NpDn/Me97p2Vn6kSZ0mO1yES1FZ/vHn7xWUl/lmA6p+R0veuYgApyPyg1ZfZSsdV2TAjQD5CEVjG47qEYcIFYUg3jlz50xomEUe2ODcxfOWRWHsvEtE0Whjd8unW1GVLfAmuJz56mt3PSpZjKgy3aOR5rUzqMXlg1bVKVmQgkd66ldDiKgXPDQyQuKbXqmcPo63y7SsFehQj3D+Kmu1Z6xcZaHhnD2ll77YNP5KH/Z/SS7s+SRpwkNn341dmAR0wSwreeTQ4Ao+uditZqgOfno6fqXfl353cY1Nb8fOgrxnMUCAjvah0bjstCuaHi6kq9I/3sGMshpd/9cIGUHkQ7V1ZIjf3YAQBa0I7ASaOIs7fpnzNlLnBCRk+em2UGTGpUm3EA1yPTidFow2Ro/DgUCkj3XObJ6EmBsij9tOEX1eHYnyi5pMwiYTfbyW+D/UuzTMS7Z9bVRRkFQO2OEquLw1kEsbZizEs5pIt5b7a4fnc4IypQi7CfnNoQbTexxkiy4SeUcwv4Wq0Jjvx+dKxfoSS2HJ3+luxjz55IW4736rjvqCSpuRIMTwTmGzwOdIsawxS6sWnlPdRQdfdqsQCtSk62dkctiWyhTmNW9E599j5GsmOFgK4V4LzHCLwfQ2hElSjFJJc1DnVRjUMY1Bkghku+dSLuNFXomB3UdIS5+iyccHrNrBL/JCcy/+tfu0Yn9HAuN7Ko7B5WIBsODK11Z9DYRAncTKEsi6c/33fWUOTAFCtXYBhV+zK8KZp3TQ0pXBJIHgO7EMlNtZD0Cs9HqkbjkhcDvuSh3Z/S01qgKJfUPxbXABGB+FmotkC2dq8liVKKy2h+U74oiibdzdZIUFoe6Qw3tthkmFwVOC0Lsz+MyR3aNcfR71zbnwgNnygo+QZNXcO5GoGr1KFWDJlOC3B3BxZl1q0jdq6NQ5J9fJ85DEYO06Ue7rB6iQYGZA7iHM9n0yZh4N2rfJ0dBfjk5D9+hTKF0nUrQ2bsUfKc3kPgPCMD0xXADmUsdIsyuT+9/2zR7SO6BdhBiPkU3x0vOQKiP64sZXSbY2McKkkPsfIcP6cXl9TDDCYgnc5wyC0P6SOCDPK0wRT+fjT39W5lMniO+yNhyYLlKaUNscA2GwC3/JztnWzNqig4VmMckDzmRsl0sba6pcinCYG+atjj20jEozqyUbcKHHCC5kVyHaL85YAknZdN3ndV38l6AKETb+SJwVbAgfwHgv3jyNgM1Ju9xgm5/RzTLPC4PgcjcgyhfyzCVwI7VfI60KMtb72hERQdY19OUupMK2VZtFR95CWjLW6WrQ35PdgWUoIe+rMsVBmdN6UUSC6HPTzsp+z/Ym7QURGQPYbS8vbBiiT8NKZn3NmUEp534Ufvff1UCxMFW85TNZLyvmgklD/Z1O8Skouhkmh7IHeR8/Uwr/NXLEsIDcHQW+AwX7F0snvgUe2pb9YXGrJSj1h0muJRZpRUyWm5cC07vcz7IzlDU9u0MO98YFnyWSnJVoQ4moIxE0jXx7tbH1fA4nO8Ggwdjy95fX9xD+H0GAdvEJOvMYgO0dr7W1csFKBjHVKSTsxfDTuxK/wRGg==,iv:e5f3W2cX/wB/KOVfdf+lteJajBZPyNxYa272/ThHRv0=,tag:AtjtDFyAbVe1InP2qxCqsQ==,type:str]
        githubConfigUrl: https://github.com/truecharts
        controllerServiceAccount:
            name: actions-runner-controller
            namespace: actions-runner-controller
        template:
            spec:
                containers:
                    - name: runner
                      image: ghcr.io/truecharts/charts-ci:latest@sha256:7541472ba15b8488c54651ef028cbfc286d9a0c72fc066500ae2c6cef60ba84b
                      command:
                        - /home/runner/run.sh
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQit6VTQvVktqcGhmR2Fa
            WUtlZ09LQldxeDc1YkpIYVJNNUpIL3JkNEhNCktydjd4LzYxQmhadTVqUFNkUGEx
            Vmg1KzhKRUw5UHNzOFBKNDkxVTJNMTQKLS0tIFIyWFpEWU9EVjh0VjMxdlh5VG1k
            dHVTMGN3ME9yS29tZ0NJSFhlRHRTeXMK39VKGVi683Bh6mc+peGai8frWdBrYlr+
            0qoRFISxOKZlTgobYoF0XiyI63gSnF515rl2aP9udtXLfHrpCDvYow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T21:38:36Z"
    mac: ENC[AES256_GCM,data:ChI/JC8JOgUB5KT3vUpccjVpLvXTtkNN9C8EkcC/lbXmkh9swE58WBnb7SBCgOUHrMDcpAM2MA0jf0z+CjlwXZA01A3baNZmvrskhJ0DIpzxFXfew7jiV+DGisq6W0r4cUZLxQs4lurZ3WB48Vdx8vhIkFivcM0Y8GBE28NKTQ8=,iv:ZcYu9bcJ8hdbgbuwZEU2oCO+kt8VZzxZwQnIZTtC4J4=,tag:aKBIFtz8JKLt0WkzCbGppQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
