---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
  namespace: spegel
spec:
  interval: 30m
  chart:
    spec:
      chart: spegel
      version: 2.0.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    securityContext:
      container:
        runAsUser: 0
        runAsGroup: 0
        readOnlyRootFilesystem: true
    pod:
      fsGroup: 0
    persistence:
      containerd-content:
        enabled: true
        type: hostPath
        mountPath: "{{ .Values.spegel.containerdContentPath }}"
        hostPath: "{{ .Values.spegel.containerdContentPath }}"
        hostPathType: Directory
        readOnly: true
      containerd-config:
        enabled: true
        type: hostPath
        hostPath: "{{ .Values.spegel.containerdRegistryConfigPath }}"
        hostPathType: DirectoryOrCreate
        targetSelector:
          main:
            configuration:
              mountPath: "{{ .Values.spegel.containerdRegistryConfigPath }}"
