---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-volsync
  namespace: flux-system
spec:
  path: ./cluster/system/volsync/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m
