apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: rook-ceph-cluster
    namespace: rook-ceph
spec:
    interval: 30m
    timeout: 15m
    releaseName: rook-ceph-cluster
    chart:
        spec:
            # renovate: registryUrl=https://charts.rook.io/release
            chart: rook-ceph-cluster
            version: v1.16.6
            sourceRef:
                kind: HelmRepository
                name: rook-ceph
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            retries: 3
    values:
      toolbox:
        enabled: true
      removeOSDsIfOutAndSafeToRemove: true
      monitoring:
        enabled: true
        createPrometheusRules: false
      configOverride: |
        [global]
        bdev_enable_discard = true
        bdev_async_discard = true
        osd_class_update_on_start = false
        bluestore_compression_algorithm = lz4
        bluestore_compression_mode = aggressive
        bluestore_compression_required_ratio = .875
        rbd_default_stripe_unit = 65536
        rbd_default_stripe_count = 16
      cephClusterSpec:
        mgr:
          count: 3
          allowMultiplePerNode: false
        mon:
          count: 3
          allowMultiplePerNode: false
        resources:
          mgr:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 2Gi
          mon:
            requests:
              cpu: 50m
              memory: 512Mi
            limits:
              memory: 1Gi
          osd:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              memory: 6Gi
          prepareosd:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 51Mi
          mgr-sidecar:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
          crashcollector:
            requests:
              cpu: "25m"
              memory: "49M"
            limits:
              memory: "64M"
          logcollector:
            requests:
              cpu: "25m"
              memory: "49M"
            limits:
              memory: "1G"
          cleanup:
            requests:
              cpu: "25m"
              memory: "49M"
            limits:
              memory: "1G"

        crashCollector:
          disable: false

        dashboard:
          enabled: true
          urlPrefix: /
          ssl: false

        storage:
          useAllNodes: true
          useAllDevices: true
          allowDeviceClassUpdate: true
          allowOsdCrushWeightUpdate: true
          enableCrushUpdates: true
          # when onlyApplyOSDPlacement is false, will merge both placement.All() and storageClassDeviceSets.Placement
          onlyApplyOSDPlacement: false
          config:
            deviceClass: nvme

      ingress:
        dashboard:
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            cert-manager.io/cluster-issuer: le-prod
            cert-manager.io/private-key-rotation-policy: Always
            traefik.ingress.kubernetes.io/router.tls: 'true'
            traefik.ingress.kubernetes.io/router.middlewares: traefik-chain-basic@kubernetescrd,traefik-local@kubernetescrd
          tls:
            - hosts:
                - rook.${DOMAIN_0}
              secretName: rook-ceph-dashboard
          host:
            name: "rook.${DOMAIN_0}"
            path: "/"
      cephBlockPools:
        - name: ceph-nvme
          spec:
            failureDomain: host
            deviceClass: nvme
            enableRBDStats: true
            parameters:
              compression_mode: aggressive
            replicated:
              size: 3
              requireSafeReplicaSize: false
          storageClass:
            enabled: true
            name: ceph-nvme
            isDefault: true
            reclaimPolicy: Delete
            allowVolumeExpansion: true
            volumeBindingMode: Immediate
            parameters:
              imageFormat: "2"
              imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
              csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
              csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
              csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
              csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
              csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
              csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
              csi.storage.k8s.io/fstype: ext4
      cephBlockPoolsVolumeSnapshotClass:
        enabled: true
        name: csi-ceph-blockpool
        isDefault: true
        deletionPolicy: Delete
