apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: rook-ceph-cluster
    namespace: rook-ceph
spec:
    interval: 30m
    timeout: 15m
    releaseName: rook-ceph-cluster
    chart:
        spec:
            # renovate: registryUrl=https://charts.rook.io/release
            chart: rook-ceph-cluster
            version: v1.15.5
            sourceRef:
                kind: HelmRepository
                name: rook-ceph
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            retries: 3
    values:
      toolbox:
        enabled: true
      removeOSDsIfOutAndSafeToRemove: true
      monitoring:
        enabled: true
        createPrometheusRules: false
      configOverride: |
        [global]
        bdev_enable_discard = true
        bdev_async_discard = true
        osd_class_update_on_start = false
        bluestore_compression_algorithm = lz4
        bluestore_compression_mode = aggressive
        bluestore_compression_required_ratio = .875
      cephClusterSpec:
        mgr:
          count: 3
          allowMultiplePerNode: false
        mon:
          count: 3
          allowMultiplePerNode: false
        resources:
          mgr:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 2Gi
          mon:
            requests:
              cpu: 50m
              memory: 512Mi
            limits:
              memory: 1Gi
          osd:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              memory: 6Gi
          prepareosd:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 51Mi
          mgr-sidecar:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
          crashcollector:
            requests:
              cpu: "25m"
              memory: "49M"
            limits:
              memory: "64M"
          logcollector:
            requests:
              cpu: "25m"
              memory: "49M"
            limits:
              memory: "1G"
          cleanup:
            requests:
              cpu: "25m"
              memory: "49M"
            limits:
              memory: "1G"

        crashCollector:
          disable: false

        dashboard:
          enabled: true
          urlPrefix: /
          ssl: false

        storage:
          useAllNodes: false
          useAllDevices: true
          # when onlyApplyOSDPlacement is false, will merge both placement.All() and storageClassDeviceSets.Placement
          onlyApplyOSDPlacement: false
          nodes:
            - name: k8s-worker-1
              config:
                deviceClass: nvme
                osdsPerDevice: "1"
            - name: k8s-worker-2
              config:
                deviceClass: nvme
                osdsPerDevice: "1"
            - name: k8s-worker-3
              config:
                deviceClass: nvme
                osdsPerDevice: "1"
            - name: k8s-worker-4
              config:
                deviceClass: nvme
                osdsPerDevice: "1"

      ingress:
        dashboard:
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            cert-manager.io/cluster-issuer: ks-le-prod
            cert-manager.io/private-key-rotation-policy: Always
            traefik.ingress.kubernetes.io/router.tls: 'true'
            traefik.ingress.kubernetes.io/router.middlewares: traefik-chain-basic@kubernetescrd,traefik-bouncer@kubernetescrd,traefik-local@kubernetescrd
          tls:
            - hosts:
                - rook.${BASE_DOMAIN}
              secretName: rook-ceph-dashboard
          host:
            name: "rook.${BASE_DOMAIN}"
            path: "/"
      cephBlockPools:
        - name: ceph-nvme
          spec:
            failureDomain: host
            deviceClass: nvme
            enableRBDStats: true
            parameters:
              compression_mode: agressive
            replicated:
              size: 3
              requireSafeReplicaSize: false
          storageClass:
            enabled: true
            name: ceph-nvme
            isDefault: true
            reclaimPolicy: Delete
            allowVolumeExpansion: true
            volumeBindingMode: Immediate
            parameters:
              imageFormat: "2"
              imageFeatures: layering
              csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
              csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
              csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
              csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
              csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
              csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
              csi.storage.k8s.io/fstype: ext4
      cephBlockPoolsVolumeSnapshotClass:
        enabled: true
        name: csi-ceph-blockpool
        isDefault: true
        deletionPolicy: Delete


      cephFileSystems:
        - name: ceph-filesystem
          spec:
            metadataPool:
              deviceClass: nvme
              replicated:
                size: 3
            dataPools:
              - failureDomain: host
                name: data0
                # deviceClass: nvme
                replicated:
                  size: 1
            metadataServer:
              activeCount: 1
              activeStandby: true
              priorityClassName: system-cluster-critical
              resources:
                requests:
                  cpu: 100m
                  memory: 1Gi
                limits:
                  memory: 4Gi
              placement:
                topologySpreadConstraints:
                - maxSkew: 1
                  topologyKey: kubernetes.io/hostname
                  whenUnsatisfiable: DoNotSchedule
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: ceph-mds
                      app.kubernetes.io/part-of: ceph-filesystem
          storageClass:
            enabled: true
            isDefault: false
            name: ceph-filesystem
            reclaimPolicy: Delete
            allowVolumeExpansion: true
            pool: data0
            volumeBindingMode: Immediate
            mountOptions: []
            parameters:
              csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
              csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
              csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
              csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
              csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
              csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
      cephFileSystemVolumeSnapshotClass:
        enabled: true
        name: csi-ceph-filesystem
        isDefault: false
        deletionPolicy: Delete
      
      cephObjectStores:
        - name: ceph-objectstore
          # see https://github.com/rook/rook/blob/master/Documentation/CRDs/Object-Storage/ceph-object-store-crd.md#object-store-settings for available configuration
          spec:
            metadataPool:
              failureDomain: host
              deviceClass: nvme
              replicated:
                size: 3
            dataPool:
              failureDomain: host
              # deviceClass: nvme
              replicated:
                size: 3
            preservePoolsOnDelete: true
            gateway:
              port: 80
              resources:
                limits:
                  memory: "2Gi"
                requests:
                  cpu: "1000m"
                  memory: "1Gi"
              # securePort: 443
              # sslCertificateRef:
              instances: 1
              priorityClassName: system-cluster-critical
          storageClass:
            enabled: true
            name: ceph-objectstore
            reclaimPolicy: Delete
            volumeBindingMode: "Immediate"
            annotations: {}
            labels: {}
            # see https://github.com/rook/rook/blob/master/Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim.md#storageclass for available configuration
          ingress:
            # Enable an ingress for the ceph-objectstore
            enabled: false
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              cert-manager.io/cluster-issuer: ks-le-prod
              cert-manager.io/private-key-rotation-policy: Always
              traefik.ingress.kubernetes.io/router.tls: 'true'
              traefik.ingress.kubernetes.io/router.middlewares: traefik-chain-basic@kubernetescrd,traefik-bouncer@kubernetescrd,traefik-local@kubernetescrd
            tls:
              - hosts:
                  - s3.${BASE_DOMAIN}
                secretName: rook-ceph-s3
            host:
              name: "s3.${BASE_DOMAIN}"
              path: "/"
            