apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: docker-registry
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/core/docker-registry/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

