apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: longhorn
    namespace: longhorn-system
spec:
    interval: 5m
    releaseName: longhorn
    chart:
        spec:

            chart: longhorn
            version: 1.7.2
            sourceRef:
                kind: HelmRepository
                name: longhorn
                namespace: flux-system
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values: 
      defaultSettings:
        # Increase to 3 for a multi-node cluster
        defaultReplicaCount: 2
        # Overprovisioning might be needed when using volsync
        storageOverProvisioningPercentage: 100000
        v2DataEngine: true
      persistence:
        # Set to false to pick another CSI as default
        defaultClass: false
        # Increase to 3 for a multi-node cluster
        defaultClassReplicaCount: 2