# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: runix
    namespace: flux-system
spec:
    interval: 30m
    url: https://helm.runix.net
    timeout: 3m
