# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: tf-controller
    namespace: flux-system
spec:
    interval: 30m
    url: https://weaveworks.github.io/tf-controller/
    timeout: 3m
