# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: truecharts
    namespace: flux-system
spec:
    type: oci
    interval: 5m
    url: oci://tccr.io/truecharts
