# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: reloader
    namespace: system
spec:
  interval: 15m
  chart:
      spec:
          chart: reloader
          version: 1.3.0
          sourceRef:
              kind: HelmRepository
              name: stakater
              namespace: flux-system
          interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
      createNamespace: true
      remediation:
          retries: 3
  upgrade:
      cleanupOnFail: true
      remediation:
          retries: 3
  uninstall:
      keepHistory: false
