---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thanos
  namespace: thanos
spec:
  interval: 15m
  chart:
    spec:
      chart: thanos
      version: 17.13.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    objstoreConfig:
      type: S3
      config:
        bucket: "${S3PREFIX}-thanos"
        endpoint: "192.168.10.21:9000"
        insecure: true
        access_key: "${S3ID_THANOS}"
        secret_key: "${S3KEY_THANOS}"
    query:
      replicaLabel: [prometheus_replica] # (2)
      dnsDiscovery:
        sidecarsService: prometheus-operated #prometheus-kube-prometheus-thanos-discovery # (3)
        sidecarsNamespace: kube-prometheus-stack
    bucketweb:
      enabled: true # (4)
    compactor:
      enabled: true # (5)
    storegateway:
      enabled: true # (6)
    ruler:
      enabled: false
    metrics: # (8)
      enabled: true
      serviceMonitor:
        enabled: true


