apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-external
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/networking/nginx-external/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

