---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clusterissuer
  namespace: clusterissuer
spec:
  interval: 15m
  chart:
    spec:
      chart: clusterissuer
      version: 4.2.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    clusterIssuer:
      selfSigned:
        enabled: true
        name: "selfsigned"
      ACME:
        - name: tc-le-staging
          # Used for both logging in to the DNS provider AND ACME registration
          email: "${EMAIL}"
          server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
          # Options: HTTP01, cloudflare, route53, akamai, digitalocean, rfc2136, acmedns
          type: "cloudflare"
          # for cloudflare
          cfapitoken: "${CLOUDFLARE_TOKEN}"
        - name: tc-le-prod
          # Used for both logging in to the DNS provider AND ACME registration
          email: "${EMAIL}"
          server: 'https://acme-v02.api.letsencrypt.org/directory'
          # Options: HTTP01, cloudflare, route53, akamai, digitalocean, rfc2136, acmedns
          type: "cloudflare"
          # for cloudflare
          cfapitoken: "${CLOUDFLARE_TOKEN}"

    clusterCertificates:
      # Namespaces in which the certificates must be available
      # Accepts comma-separated regex expressions
      # replicationNamespaces: 'ix-.*'
      certificates:
        - name: tc-wildcard
          enabled: false
          certificateIssuer: tc-le-prod
          hosts:
            - truecharts.org
            - '*.truecharts.org'
