name: Automerge and Approve

on:
  workflow_run:
    workflows: ["Placeholder"]  # Name of the main CI workflow
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@7961b8b5eec56cc088c140b56d864285eabd3f67" # v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          UPDATE_RETRIES: 24
          UPDATE_RETRY_SLEEP: 60000
          MERGE_METHOD: "squash"
