---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: unpoller
  namespace: unpoller
spec:
  interval: 15m
  chart:
    spec:
      chart: unpoller
      version: 10.3.3
      sourceRef:
        kind: HelmRepository
        name: truechartsoci
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fallbackDefaults:
      accessModes:
        - ReadWriteMany
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                UP_UNIFI_DEFAULT_URL: "https://192.168.10.1"
                UP_UNIFI_DEFAULT_USER: "unpoller"
                UP_UNIFI_DEFAULT_PASS: "y2GJTb44YvuTttaB"
