
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-series-nfs-pv
  namespace: media
spec:
  storageClassName: media-series-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.21
    path: "/mnt/tank/library/series"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-series-nfs-pvc
  namespace: media
spec:
  storageClassName: media-series-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-movies-nfs-pv
  namespace: media
spec:
  storageClassName: media-movies-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.21
    path: "/mnt/tank/library/movies"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-movies-nfs-pvc
  namespace: media
spec:
  storageClassName: media-movies-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-music-nfs-pv
  namespace: media
spec:
  storageClassName: media-music-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.21
    path: "/mnt/tank/library/music"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-music-nfs-pvc
  namespace: media
spec:
  storageClassName: media-music-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-books-nfs-pv
  namespace: media
spec:
  storageClassName: media-books-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.21
    path: "/mnt/stor/library/books"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-books-nfs-pvc
  namespace: media
spec:
  storageClassName: media-books-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-porn-nfs-pv
  namespace: media
spec:
  storageClassName: media-porn-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.21
    path: "/mnt/stor/library/porn"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-porn-nfs-pvc
  namespace: media
spec:
  storageClassName: media-porn-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-castlefest-nfs-pv
  namespace: media
spec:
  storageClassName: media-castlefest-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.21
    path: "/mnt/stor/library/castlefest"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-castlefest-nfs-pvc
  namespace: media
spec:
  storageClassName: media-castlefest-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi