apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library
  namespace: media
  finalizers:
    - kjeldschouten.nl/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-filesystem
  volumeMode: Filesystem
