apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: volsync
    namespace: volsync
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: volsync
            version: 1.0.1
            sourceRef:
                kind: HelmRepository
                name: truechartsoci
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        remediation:
            retries: 3
