apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: apps
    namespace: flux-system
spec:
    interval: 10m0s
    dependsOn:
        - kube-system
        - crds
        - operators
        - system
        - core
    path: ./cluster/apps
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
    decryption:
        provider: sops
        secretRef:
            name: sops-age
